# Copyright 2025 Damien Davison & Michael Maillet, Recursive AI Devs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Synthetic Data Generator - "The Dreamer"
=========================================

Agent 1.1 of the Conjecture Generation Team

Based on the AlphaGeometry paradigm, continuously generates random geometric
or algebraic premises and attempts to derive conclusions using Phase 2
symbolic engines.

Function: Produces millions of "synthetic theorems" - statements that are
logically true but potentially trivial. Creates a massive dataset of
premise-conclusion pairs to train downstream agent intuition.

Output: Stream of SyntheticTheorem objects containing premises, derivation
steps, and conclusions.

Reference: Phase 6 must engineer the capacity for novel mathematical discovery.docx, Section 1
Reference: Phase_6_Build_Order_Breakdown.md, Step 1
"""

import logging
import sympy as sp
import random
import hashlib
from dataclasses import dataclass, field
from typing import List, Optional, Generator, Dict, Any, Tuple
from datetime import datetime
from enum import Enum

# Initialize module logger
try:
    from symbo_agentic_reasoners_logging import get_logger
    logger = get_logger('symbo_agentic_reasoners.phase6.conjecture_generation.synthetic_data_generator')
except ImportError:
    logger = logging.getLogger(__name__)


class TheoremDomain(Enum):
    """Mathematical domains for synthetic theorem generation"""
    ALGEBRA = 'algebra'
    GEOMETRY = 'geometry'
    NUMBER_THEORY = 'number_theory'
    ANALYSIS = 'analysis'
    COMBINATORICS = 'combinatorics'
    LINEAR_ALGEBRA = 'linear_algebra'


@dataclass
class SyntheticTheorem:
    """
    A theorem generated by the Synthetic Data Generator.

    Based on AlphaGeometry paradigm: randomly sample premises
    and derive conclusions using symbolic engines.

    Attributes:
        theorem_id: Unique identifier for the theorem
        premises: List of SymPy expressions representing premises
        conclusion: The derived SymPy expression conclusion
        derivation_steps: List of steps taken to derive the conclusion
        domain: Mathematical domain of the theorem
        complexity_score: 0-1 score indicating theorem complexity
        novelty_score: 0-1 score indicating potential novelty (set by PatternRecognizer)
        generation_timestamp: When the theorem was generated
    """
    theorem_id: str
    premises: List[sp.Expr]
    conclusion: sp.Expr
    derivation_steps: List[str]
    domain: str
    complexity_score: float
    novelty_score: float = 0.0
    generation_timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_natural_language(self) -> str:
        """Convert to human-readable statement"""
        if self.premises:
            premises_str = " AND ".join([str(p) for p in self.premises])
            return f"IF {premises_str} THEN {self.conclusion}"
        return f"STATEMENT: {self.conclusion}"

    def compute_hash(self) -> str:
        """Deterministic hash for deduplication"""
        content = f"{sorted([str(p) for p in self.premises])}|{self.conclusion}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary"""
        return {
            'theorem_id': self.theorem_id,
            'premises': [str(p) for p in self.premises],
            'conclusion': str(self.conclusion),
            'derivation_steps': self.derivation_steps,
            'domain': self.domain,
            'complexity_score': self.complexity_score,
            'novelty_score': self.novelty_score,
            'generation_timestamp': self.generation_timestamp.isoformat(),
            'natural_language': self.to_natural_language()
        }


class SyntheticDataGenerator:
    """
    Agent 1.1: The Dreamer - AlphaGeometry-style synthetic theorem generator

    Continuously generates random mathematical premises and derives conclusions
    using symbolic manipulation to create training data for conjecture discovery.

    Key capabilities:
    - Multi-domain theorem generation (algebra, geometry, number theory, analysis)
    - Complexity-aware generation with configurable parameters
    - Streaming generation for memory efficiency
    - Deduplication via content hashing

    Reference: Phase 6 must engineer the capacity for novel mathematical discovery.docx
    """

    # Statistics tracking
    stats: Dict[str, int]

    def __init__(self, symbolic_engine=None, df_client=None, seed: int = None):
        """
        Initialize the Synthetic Data Generator.

        Args:
            symbolic_engine: Phase 2 symbolic engine for derivations
            df_client: Directory Facilitator client for service discovery
            seed: Random seed for reproducibility
        """
        self.symbolic_engine = symbolic_engine
        self.df = df_client
        self.theorem_count = 0
        self.seen_hashes = set()

        if seed is not None:
            random.seed(seed)

        # Symbol pools for different domains
        self.algebra_symbols = sp.symbols('x y z a b c n m k')
        self.geometry_symbols = sp.symbols('A B C D P Q R theta phi alpha beta')
        self.analysis_symbols = sp.symbols('f g h epsilon delta t s')
        self.number_symbols = sp.symbols('p q r n m k', integer=True, positive=True)

        # Binary operations for expression generation
        self.binary_ops = [
            lambda a, b: a + b,
            lambda a, b: a * b,
            lambda a, b: a - b,
            lambda a, b: a / b if b != 0 else a,
            lambda a, b: a ** b if isinstance(b, int) and 0 <= b <= 3 else a ** 2,
            lambda a, b: sp.Eq(a, b),
        ]

        # Unary operations
        self.unary_ops = [
            lambda a: a ** 2,
            lambda a: sp.sqrt(sp.Abs(a)),
            lambda a: sp.sin(a),
            lambda a: sp.cos(a),
            lambda a: sp.exp(a),
            lambda a: sp.log(sp.Abs(a) + 1),
        ]

        # Statistics
        self.stats = {
            'total_generated': 0,
            'algebra': 0,
            'geometry': 0,
            'number_theory': 0,
            'analysis': 0,
            'combinatorics': 0,
            'linear_algebra': 0,
            'duplicates_filtered': 0,
            'generation_errors': 0
        }

    def generate_stream(self, batch_size: int = 1000, max_theorems: int = None) -> Generator[SyntheticTheorem, None, None]:
        """
        Generate synthetic theorems continuously as a stream.

        Args:
            batch_size: Number of theorems to attempt per batch
            max_theorems: Maximum theorems to generate (None for infinite)

        Yields:
            SyntheticTheorem objects that pass validation
        """
        count = 0
        while max_theorems is None or count < max_theorems:
            batch = [self._generate_single() for _ in range(batch_size)]
            valid_theorems = [t for t in batch if t is not None]

            for theorem in valid_theorems:
                if max_theorems is not None and count >= max_theorems:
                    return
                yield theorem
                count += 1

    def generate_batch(self, size: int = 100, domain: str = None) -> List[SyntheticTheorem]:
        """
        Generate a batch of synthetic theorems.

        Args:
            size: Number of theorems to generate
            domain: Optional domain restriction

        Returns:
            List of valid SyntheticTheorem objects
        """
        theorems = []
        attempts = 0
        max_attempts = size * 10  # Allow for failures

        while len(theorems) < size and attempts < max_attempts:
            attempts += 1
            if domain:
                theorem = self._generate_for_domain(domain)
            else:
                theorem = self._generate_single()

            if theorem is not None:
                theorems.append(theorem)

        return theorems

    def _generate_single(self) -> Optional[SyntheticTheorem]:
        """Generate a single synthetic theorem from a random domain"""
        try:
            domain = random.choice(list(TheoremDomain))
            return self._generate_for_domain(domain.value)
        except (TypeError, ValueError, AttributeError, KeyError) as e:
            # Data/conversion errors during generation
            logger.debug(f"Generation data error in _generate_single: {e}")
            self.stats['generation_errors'] += 1
            return None
        except (sp.SympifyError, RecursionError) as e:
            # SymPy/recursion errors during generation
            logger.debug(f"Generation sympy error in _generate_single: {e}")
            self.stats['generation_errors'] += 1
            return None

    def _generate_for_domain(self, domain: str) -> Optional[SyntheticTheorem]:
        """Generate a theorem for a specific domain"""
        generators = {
            'algebra': self._generate_algebra_theorem,
            'geometry': self._generate_geometry_theorem,
            'number_theory': self._generate_number_theory_theorem,
            'analysis': self._generate_analysis_theorem,
            'combinatorics': self._generate_combinatorics_theorem,
            'linear_algebra': self._generate_linear_algebra_theorem
        }

        generator = generators.get(domain, self._generate_algebra_theorem)

        try:
            theorem = generator()
            if theorem is not None:
                # Check for duplicates
                thm_hash = theorem.compute_hash()
                if thm_hash in self.seen_hashes:
                    self.stats['duplicates_filtered'] += 1
                    return None
                self.seen_hashes.add(thm_hash)

                self.stats['total_generated'] += 1
                self.stats[domain] = self.stats.get(domain, 0) + 1

            return theorem
        except (TypeError, ValueError, AttributeError, KeyError) as e:
            # Data/conversion errors during domain generation
            logger.debug(f"Generation data error for domain {domain}: {e}")
            self.stats['generation_errors'] += 1
            return None
        except (sp.SympifyError, RecursionError, NotImplementedError) as e:
            # SymPy/recursion errors during domain generation
            logger.debug(f"Generation sympy error for domain {domain}: {e}")
            self.stats['generation_errors'] += 1
            return None

    def _generate_algebra_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate algebraic identity or relation"""
        x, y, z, a, b, c = sp.symbols('x y z a b c')

        template = random.choice(['polynomial_identity', 'equation_solution', 'factorization', 'expansion'])

        if template == 'polynomial_identity':
            # Generate polynomial identities like (a+b)^2 = a^2 + 2ab + b^2
            n = random.randint(2, 4)
            lhs = (a + b) ** n
            rhs = sp.expand(lhs)
            premises = []
            conclusion = sp.Eq(lhs, rhs)
            derivation = ['expand', 'simplify']

        elif template == 'equation_solution':
            # Generate equation and its solution
            degree = random.randint(1, 2)
            coeffs = [random.randint(-5, 5) for _ in range(degree + 1)]
            poly = sum(c * x**i for i, c in enumerate(coeffs))

            premises = [sp.Eq(poly, 0)]
            try:
                solutions = sp.solve(poly, x)
                if solutions:
                    conclusion = sp.Eq(x, solutions[0])
                else:
                    return None
            except (TypeError, ValueError, NotImplementedError) as e:
                logger.debug(f"Could not solve equation: {e}")
                return None
            derivation = ['solve', 'simplify']

        elif template == 'factorization':
            # Generate factorable polynomial
            r1, r2 = random.randint(-5, 5), random.randint(-5, 5)
            poly = (x - r1) * (x - r2)
            expanded = sp.expand(poly)

            premises = []
            conclusion = sp.Eq(expanded, poly)
            derivation = ['factor']

        else:  # expansion
            # Binomial expansion
            n = random.randint(2, 4)
            expr = (x + y) ** n
            expanded = sp.expand(expr)

            premises = []
            conclusion = sp.Eq(expr, expanded)
            derivation = ['binomial_theorem', 'expand']

        self.theorem_count += 1

        return SyntheticTheorem(
            theorem_id=f"synth_alg_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=derivation,
            domain="algebra",
            complexity_score=self._compute_complexity(premises, conclusion)
        )

    def _generate_geometry_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate geometric relation"""
        a, b, c, theta = sp.symbols('a b c theta', positive=True, real=True)

        template = random.choice(['pythagorean', 'law_of_cosines', 'law_of_sines',
                                  'area_formula', 'angle_sum', 'trig_identity'])

        if template == 'pythagorean':
            premises = [sp.Eq(sp.Symbol('angle_C'), sp.pi/2)]  # Right angle
            conclusion = sp.Eq(c**2, a**2 + b**2)
            derivation = ['pythagorean_theorem']

        elif template == 'law_of_cosines':
            premises = []
            conclusion = sp.Eq(c**2, a**2 + b**2 - 2*a*b*sp.cos(theta))
            derivation = ['law_of_cosines']

        elif template == 'law_of_sines':
            alpha, beta = sp.symbols('alpha beta', positive=True, real=True)
            premises = []
            conclusion = sp.Eq(a/sp.sin(alpha), b/sp.sin(beta))
            derivation = ['law_of_sines']

        elif template == 'area_formula':
            s = (a + b + c) / 2
            area = sp.sqrt(s * (s-a) * (s-b) * (s-c))
            premises = [sp.Gt(a + b, c), sp.Gt(b + c, a), sp.Gt(a + c, b)]
            conclusion = sp.Eq(sp.Symbol('Area'), area)
            derivation = ['herons_formula']

        elif template == 'angle_sum':
            alpha, beta, gamma = sp.symbols('alpha beta gamma', positive=True)
            premises = [sp.Symbol('triangle')]
            conclusion = sp.Eq(alpha + beta + gamma, sp.pi)
            derivation = ['angle_sum_theorem']

        else:  # trig_identity
            premises = []
            identity = random.choice([
                sp.Eq(sp.sin(theta)**2 + sp.cos(theta)**2, 1),
                sp.Eq(sp.tan(theta), sp.sin(theta)/sp.cos(theta)),
                sp.Eq(sp.sin(2*theta), 2*sp.sin(theta)*sp.cos(theta)),
                sp.Eq(sp.cos(2*theta), sp.cos(theta)**2 - sp.sin(theta)**2)
            ])
            conclusion = identity
            derivation = ['trig_identity']

        self.theorem_count += 1

        return SyntheticTheorem(
            theorem_id=f"synth_geo_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=derivation,
            domain="geometry",
            complexity_score=self._compute_complexity(premises, conclusion)
        )

    def _generate_number_theory_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate number-theoretic relation"""
        n, m, p, k = sp.symbols('n m p k', integer=True, positive=True)

        template = random.choice(['divisibility', 'modular_arithmetic', 'sum_formula',
                                  'gcd_property', 'prime_property'])

        if template == 'divisibility':
            base = random.randint(2, 10)
            power = random.randint(2, 4)
            premises = [sp.Eq(n % base, 0)]
            conclusion = sp.Eq((n**power) % base, 0)
            derivation = ['divisibility_rule']

        elif template == 'modular_arithmetic':
            # Fermat's little theorem variant
            premises = [sp.Eq(sp.gcd(n, p), 1), sp.Symbol('p_is_prime')]
            conclusion = sp.Eq(sp.Mod(n**(p-1), p), 1)
            derivation = ['fermats_little_theorem']

        elif template == 'sum_formula':
            formula_type = random.choice(['arithmetic', 'squares', 'cubes'])
            premises = [sp.Gt(n, 0)]

            if formula_type == 'arithmetic':
                conclusion = sp.Eq(sp.Sum(k, (k, 1, n)), n*(n+1)/2)
            elif formula_type == 'squares':
                conclusion = sp.Eq(sp.Sum(k**2, (k, 1, n)), n*(n+1)*(2*n+1)/6)
            else:
                conclusion = sp.Eq(sp.Sum(k**3, (k, 1, n)), (n*(n+1)/2)**2)
            derivation = ['sum_formula', 'induction']

        elif template == 'gcd_property':
            a, b = sp.symbols('a b', integer=True, positive=True)
            premises = []
            conclusion = sp.Eq(sp.gcd(a, b), sp.gcd(b, sp.Mod(a, b)))
            derivation = ['euclidean_algorithm']

        else:  # prime_property
            premises = [sp.Symbol('p_is_prime'), sp.Gt(p, 2)]
            conclusion = sp.Eq(sp.Mod(p, 2), 1)  # All primes > 2 are odd
            derivation = ['prime_definition']

        self.theorem_count += 1

        return SyntheticTheorem(
            theorem_id=f"synth_nt_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=derivation,
            domain="number_theory",
            complexity_score=self._compute_complexity(premises, conclusion)
        )

    def _generate_analysis_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate calculus/analysis theorem"""
        x, a, n, t = sp.symbols('x a n t')

        template = random.choice(['derivative', 'integral', 'series', 'limit',
                                  'fundamental_theorem'])

        if template == 'derivative':
            funcs = [
                (sp.sin(x), sp.cos(x)),
                (sp.cos(x), -sp.sin(x)),
                (sp.exp(x), sp.exp(x)),
                (sp.log(x), 1/x),
                (x**n, n*x**(n-1)),
                (sp.sin(x)**2, 2*sp.sin(x)*sp.cos(x))
            ]
            f, df = random.choice(funcs)
            premises = []
            conclusion = sp.Eq(sp.Derivative(f, x), df)
            derivation = ['differentiation_rule']

        elif template == 'integral':
            funcs = [
                (x**n, x**(n+1)/(n+1)),
                (sp.sin(x), -sp.cos(x)),
                (sp.cos(x), sp.sin(x)),
                (sp.exp(x), sp.exp(x)),
                (1/x, sp.log(sp.Abs(x)))
            ]
            f, integral_f = random.choice(funcs)
            premises = [sp.Ne(n, -1)] if n in f.free_symbols else []
            conclusion = sp.Eq(sp.Integral(f, x), integral_f)
            derivation = ['integration_rule']

        elif template == 'series':
            # Taylor series for common functions
            series_funcs = [
                (sp.exp(x), sum(x**k / sp.factorial(k) for k in range(6))),
                (sp.sin(x), sum((-1)**k * x**(2*k+1) / sp.factorial(2*k+1) for k in range(4))),
                (sp.cos(x), sum((-1)**k * x**(2*k) / sp.factorial(2*k) for k in range(4)))
            ]
            f, series = random.choice(series_funcs)
            premises = []
            conclusion = sp.Eq(sp.series(f, x, 0, 6).removeO(), series)
            derivation = ['taylor_series']

        elif template == 'limit':
            limits = [
                (sp.sin(x)/x, 0, 1),
                ((1 + 1/n)**n, sp.oo, sp.E),
                ((sp.exp(x) - 1)/x, 0, 1)
            ]
            expr, point, value = random.choice(limits)
            var = n if point == sp.oo else x
            premises = []
            conclusion = sp.Eq(sp.Limit(expr, var, point), value)
            derivation = ['limit_definition']

        else:  # fundamental_theorem
            f = sp.Function('f')
            F = sp.Function('F')
            premises = [sp.Eq(sp.Derivative(F(x), x), f(x))]
            conclusion = sp.Eq(sp.Integral(f(t), (t, a, x)), F(x) - F(a))
            derivation = ['fundamental_theorem_of_calculus']

        self.theorem_count += 1

        return SyntheticTheorem(
            theorem_id=f"synth_ana_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=derivation,
            domain="analysis",
            complexity_score=self._compute_complexity(premises, conclusion)
        )

    def _generate_combinatorics_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate combinatorics theorem"""
        n, k, r = sp.symbols('n k r', integer=True, nonnegative=True)

        template = random.choice(['binomial_coefficient', 'permutation', 'pascal_identity',
                                  'vandermonde', 'hockey_stick'])

        if template == 'binomial_coefficient':
            premises = [sp.Ge(n, k), sp.Ge(k, 0)]
            conclusion = sp.Eq(sp.binomial(n, k), sp.factorial(n) / (sp.factorial(k) * sp.factorial(n-k)))
            derivation = ['binomial_definition']

        elif template == 'permutation':
            premises = [sp.Ge(n, k), sp.Ge(k, 0)]
            P_n_k = sp.factorial(n) / sp.factorial(n - k)
            conclusion = sp.Eq(sp.Symbol('P(n,k)'), P_n_k)
            derivation = ['permutation_formula']

        elif template == 'pascal_identity':
            premises = [sp.Ge(n, k), sp.Ge(k, 1)]
            conclusion = sp.Eq(sp.binomial(n, k), sp.binomial(n-1, k-1) + sp.binomial(n-1, k))
            derivation = ['pascals_identity']

        elif template == 'vandermonde':
            m = sp.Symbol('m', integer=True, nonnegative=True)
            premises = []
            lhs = sp.binomial(m + n, r)
            rhs = sp.Sum(sp.binomial(m, k) * sp.binomial(n, r-k), (k, 0, r))
            conclusion = sp.Eq(lhs, rhs)
            derivation = ['vandermondes_identity']

        else:  # hockey_stick
            premises = [sp.Ge(n, r), sp.Ge(r, 0)]
            lhs = sp.Sum(sp.binomial(k, r), (k, r, n))
            rhs = sp.binomial(n + 1, r + 1)
            conclusion = sp.Eq(lhs, rhs)
            derivation = ['hockey_stick_identity']

        self.theorem_count += 1

        return SyntheticTheorem(
            theorem_id=f"synth_comb_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=derivation,
            domain="combinatorics",
            complexity_score=self._compute_complexity(premises, conclusion)
        )

    def _generate_linear_algebra_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate linear algebra theorem"""
        template = random.choice(['determinant', 'eigenvalue', 'matrix_property',
                                  'rank_nullity', 'trace_property'])

        A = sp.MatrixSymbol('A', 2, 2)
        B = sp.MatrixSymbol('B', 2, 2)
        n = sp.Symbol('n', integer=True, positive=True)

        if template == 'determinant':
            premises = []
            # det(AB) = det(A) * det(B)
            conclusion = sp.Eq(sp.Symbol('det(AB)'), sp.Symbol('det(A)') * sp.Symbol('det(B)'))
            derivation = ['determinant_multiplicative_property']

        elif template == 'eigenvalue':
            lam = sp.Symbol('lambda')
            v = sp.MatrixSymbol('v', 2, 1)
            premises = [sp.Eq(sp.Symbol('Av'), lam * sp.Symbol('v'))]
            conclusion = sp.Eq(sp.Symbol('det(A - lambda*I)'), 0)
            derivation = ['eigenvalue_definition']

        elif template == 'matrix_property':
            properties = [
                ([], sp.Eq(sp.Symbol('(AB)^T'), sp.Symbol('B^T * A^T'))),
                ([], sp.Eq(sp.Symbol('(A^-1)^T'), sp.Symbol('(A^T)^-1'))),
                ([], sp.Eq(sp.Symbol('A * A^-1'), sp.Symbol('I')))
            ]
            premises, conclusion = random.choice(properties)
            derivation = ['matrix_algebra']

        elif template == 'rank_nullity':
            premises = []
            conclusion = sp.Eq(sp.Symbol('rank(A)') + sp.Symbol('nullity(A)'), sp.Symbol('n'))
            derivation = ['rank_nullity_theorem']

        else:  # trace_property
            premises = []
            properties = [
                sp.Eq(sp.Symbol('trace(A+B)'), sp.Symbol('trace(A)') + sp.Symbol('trace(B)')),
                sp.Eq(sp.Symbol('trace(AB)'), sp.Symbol('trace(BA)')),
                sp.Eq(sp.Symbol('trace(cA)'), sp.Symbol('c') * sp.Symbol('trace(A)'))
            ]
            conclusion = random.choice(properties)
            derivation = ['trace_property']

        self.theorem_count += 1

        return SyntheticTheorem(
            theorem_id=f"synth_la_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=derivation,
            domain="linear_algebra",
            complexity_score=self._compute_complexity(premises, conclusion)
        )

    # =========================================================================
    # GRAMMAR-BASED GENERATION (Novel Expression Synthesis)
    # =========================================================================

    def _generate_grammar_based(self, domain: str = 'algebra') -> Optional[SyntheticTheorem]:
        """
        Generate theorem using context-free grammar approach.

        This creates novel expressions beyond fixed templates by:
        1. Randomly building expression trees from production rules
        2. Applying algebraic transformations
        3. Verifying the relationship holds

        This enables genuine novelty in theorem generation.
        """
        try:
            # Select symbols for this domain
            symbols = self._get_domain_symbols(domain)
            if len(symbols) < 2:
                return None

            # Generate a random expression using grammar
            expr_depth = random.randint(2, 4)
            lhs = self._generate_grammar_expr(symbols, expr_depth)

            if lhs is None:
                return None

            # Generate a related expression through transformation
            transformation, rhs = self._apply_random_transformation(lhs)

            if rhs is None or transformation is None:
                return None

            # Verify the relationship actually holds
            if not self._verify_relationship(lhs, rhs, transformation):
                return None

            # Create the theorem
            premises = []
            conclusion = sp.Eq(lhs, rhs)
            derivation = [transformation]

            self.theorem_count += 1
            self.stats['total_generated'] += 1
            self.stats['grammar_generated'] = self.stats.get('grammar_generated', 0) + 1

            return SyntheticTheorem(
                theorem_id=f"synth_gram_{self.theorem_count}",
                premises=premises,
                conclusion=conclusion,
                derivation_steps=derivation,
                domain=domain,
                complexity_score=self._compute_complexity(premises, conclusion)
            )

        except (TypeError, ValueError, RecursionError) as e:
            logger.debug(f"Grammar-based generation failed: {e}")
            return None

    def _get_domain_symbols(self, domain: str) -> tuple:
        """Get appropriate symbols for a mathematical domain."""
        domain_symbols = {
            'algebra': self.algebra_symbols,
            'geometry': self.geometry_symbols,
            'analysis': self.analysis_symbols,
            'number_theory': self.number_symbols,
            'combinatorics': self.number_symbols,
            'linear_algebra': self.algebra_symbols
        }
        return domain_symbols.get(domain, self.algebra_symbols)

    def _generate_grammar_expr(self, symbols, depth: int, current_depth: int = 0):
        """
        Generate expression using production rules.

        Grammar:
            expr -> term | expr op term
            term -> factor | term * factor | term / factor
            factor -> atom | unary(factor) | (expr)
            atom -> symbol | constant
        """
        if current_depth >= depth:
            # Base case: return an atom
            return self._generate_atom(symbols)

        # Production rule selection with weighted probabilities
        rule_choice = random.random()

        if rule_choice < 0.3:
            # Binary operation: expr op expr
            left = self._generate_grammar_expr(symbols, depth, current_depth + 1)
            right = self._generate_grammar_expr(symbols, depth, current_depth + 1)
            if left is None or right is None:
                return self._generate_atom(symbols)

            op = random.choice(self.binary_ops[:5])  # Exclude Eq from binary ops
            try:
                result = op(left, right)
                return result
            except (TypeError, ZeroDivisionError):
                return left + right

        elif rule_choice < 0.5:
            # Unary operation: func(expr)
            inner = self._generate_grammar_expr(symbols, depth, current_depth + 1)
            if inner is None:
                return self._generate_atom(symbols)

            op = random.choice(self.unary_ops)
            try:
                return op(inner)
            except (TypeError, ValueError):
                return inner ** 2

        elif rule_choice < 0.7:
            # Power expression: expr ^ small_int
            base = self._generate_grammar_expr(symbols, depth, current_depth + 1)
            if base is None:
                return self._generate_atom(symbols)
            exp = random.randint(2, 3)
            return base ** exp

        else:
            # Just an atom
            return self._generate_atom(symbols)

    def _generate_atom(self, symbols) -> sp.Expr:
        """Generate an atomic expression (symbol or constant)."""
        if random.random() < 0.7 and len(symbols) > 0:
            # Return a symbol
            return random.choice(list(symbols))
        else:
            # Return a small integer constant
            return sp.Integer(random.randint(1, 5))

    def _apply_random_transformation(self, expr) -> tuple:
        """
        Apply a random algebraic transformation to generate a related expression.

        Returns:
            (transformation_name, transformed_expression)
        """
        transformations = [
            ('expand', lambda e: sp.expand(e)),
            ('factor', lambda e: sp.factor(e)),
            ('simplify', lambda e: sp.simplify(e)),
            ('cancel', lambda e: sp.cancel(e)),
            ('trigsimp', lambda e: sp.trigsimp(e)),
            ('powsimp', lambda e: sp.powsimp(e)),
            ('collect', lambda e: sp.collect(e, list(e.free_symbols)[0]) if e.free_symbols else e),
        ]

        # Try transformations until one changes the expression
        random.shuffle(transformations)

        for name, transform in transformations:
            try:
                transformed = transform(expr)
                # Only accept if it's different but equivalent
                if transformed != expr and sp.simplify(expr - transformed) == 0:
                    return (name, transformed)
            except (TypeError, ValueError, IndexError, AttributeError):
                continue

        # Fallback: just expand
        try:
            expanded = sp.expand(expr)
            return ('expand', expanded)
        except (TypeError, ValueError):
            return (None, None)

    def _verify_relationship(self, lhs, rhs, transformation: str) -> bool:
        """Verify that the generated relationship actually holds."""
        try:
            diff = sp.simplify(lhs - rhs)
            return diff == 0
        except (TypeError, ValueError):
            return False

    def generate_novel(self, count: int = 10, domain: str = None) -> List[SyntheticTheorem]:
        """
        Generate novel theorems using grammar-based approach.

        This is the recommended method for generating theorems with genuine novelty,
        as it doesn't rely on fixed templates.

        Args:
            count: Number of theorems to generate
            domain: Optional domain restriction

        Returns:
            List of novel SyntheticTheorem objects
        """
        theorems = []
        attempts = 0
        max_attempts = count * 20  # Allow for many failures since grammar-based is exploratory

        while len(theorems) < count and attempts < max_attempts:
            attempts += 1
            target_domain = domain or random.choice(list(TheoremDomain)).value

            theorem = self._generate_grammar_based(target_domain)

            if theorem is not None:
                # Check for duplicates
                thm_hash = theorem.compute_hash()
                if thm_hash not in self.seen_hashes:
                    self.seen_hashes.add(thm_hash)
                    theorems.append(theorem)

        return theorems

    def _compute_complexity(self, premises: List[sp.Expr], conclusion: sp.Expr) -> float:
        """
        Compute complexity score for a theorem.

        Factors:
        - Expression length
        - Number of distinct symbols
        - Depth of expression tree
        - Number of premises
        """
        total_length = sum(len(str(p)) for p in premises) + len(str(conclusion))

        # Count distinct symbols
        all_symbols = set()
        for expr in premises + [conclusion]:
            if hasattr(expr, 'free_symbols'):
                all_symbols.update(expr.free_symbols)

        # Compute weighted score
        length_score = min(1.0, total_length / 300)
        symbol_score = min(1.0, len(all_symbols) / 10)
        premise_score = min(1.0, len(premises) / 5)

        complexity = 0.4 * length_score + 0.3 * symbol_score + 0.3 * premise_score

        return round(complexity, 3)

    def get_statistics(self) -> Dict[str, Any]:
        """Get generator statistics"""
        return {
            **self.stats,
            'unique_theorems': len(self.seen_hashes),
            'theorem_count': self.theorem_count
        }

    def reset(self):
        """Reset generator state"""
        self.theorem_count = 0
        self.seen_hashes.clear()
        for key in self.stats:
            self.stats[key] = 0

    def health_check(self) -> bool:
        """Check if generator is healthy"""
        try:
            theorem = self._generate_single()
            return theorem is not None
        except (TypeError, ValueError, RuntimeError) as e:
            logger.warning(f"Health check failed: {e}")
            return False
