# Copyright 2025 Michael Maillet, Damien Davison, and Sacha Davison
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
FIELD ISOMORPHISM SPECIALIST (Tier 3)
=====================================

Handles field isomorphism detection and automorphism group computation.

CAPABILITIES:
------------
- are_isomorphic: Check if two finite fields are isomorphic
- automorphism_group: Compute Galois group Gal(GF(p^n)/GF(p))
- fixed_field: Compute fixed field of subgroup
- orbit_under_automorphisms: Compute orbit of element

FORMULATION:
-----------
Isomorphism: GF(p^n) ≅ GF(q^m) iff p = q and n = m
Automorphism Group: Gal(GF(p^n)/GF(p)) = <φ> ≅ Z/nZ where φ is Frobenius
Fixed Field: Fix(H) for H ≤ Gal is the subfield fixed by all σ ∈ H

ALGORITHMIC BACKING:
-------------------
- Order comparison for isomorphism
- Frobenius powers for automorphisms
- Subgroup orbit for fixed fields

NO SYMPY - Pure native mathematical reasoning.

REFERENCE:
---------
- Lidl & Niederreiter (1997), Chapter 2: Automorphisms
- Lang (2002), Algebra, Chapter VI: Galois Theory
"""

import logging
from typing import Any, Dict, List, Optional, Set, Tuple

from symbo_agentic_reasoners.core.bdi_agent import BDIAgent, Intention
from symbo_agentic_reasoners.infrastructure.directory_facilitator import (
    DirectoryFacilitator, create_service_registration
)
from symbo_agentic_reasoners.core.blackboard import (
    Blackboard, create_entry, EntryType, EntryStatus
)
from symbo_agentic_reasoners.core.finite_fields import (
    is_prime, polynomial_mult_mod, polynomial_add
)

logger = logging.getLogger(__name__)


class FieldIsomorphismSpecialist(BDIAgent):
    """
    Field Isomorphism Specialist - Automorphisms and Galois Groups

    DIRECTIVE:
    ---------
    Handle isomorphism detection and automorphism group computation.

    OPERATIONS:
    ----------
    - are_isomorphic: Check field isomorphism
    - automorphism_group: Compute Galois group
    - fixed_field: Fixed field of automorphism subgroup
    - orbit: Orbit under automorphisms

    FORMULATION:
    -----------
    Gal(GF(p^n)/GF(p)) is cyclic of order n, generated by Frobenius.
    Fixed field of <φ^k> is GF(p^{n/k}) where k | n.

    REFERENCE:
    ---------
    - Lidl & Niederreiter (1997), Finite Fields, Chapter 2
    """

    def __init__(
        self,
        agent_id: str = 'field_isomorphism_specialist_001',
        df: Optional[DirectoryFacilitator] = None,
        blackboard: Optional[Blackboard] = None
    ):
        """Initialize Field Isomorphism Specialist."""
        super().__init__(agent_id)

        self.df = df
        self.blackboard = blackboard

        # Statistics
        self.tasks_executed = 0
        self.tasks_succeeded = 0
        self.tasks_failed = 0
        self.isomorphism_tests = 0
        self.automorphism_groups_computed = 0
        self.fixed_fields_computed = 0
        self.orbits_computed = 0

        if self.df:
            self._register_services()

    def _register_services(self):
        """Register services with Directory Facilitator."""
        registration = create_service_registration(
            service_type='math.algebra.finite_fields.isomorphism',
            agent_id=self.agent_id,
            algorithm='galois_automorphism',
            cost='medium',
            instance=self,
            type='specialist',
            tier='3',
            operations='isomorphism_automorphism_fixed_orbit'
        )
        self.df.register(registration)
        logger.info(f"[{self.agent_id}] Registered as field isomorphism specialist")

    # ========================================
    # Core Operations
    # ========================================

    def are_isomorphic(
        self,
        field1: Dict[str, Any],
        field2: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Check if two finite fields are isomorphic.

        GF(p^n) ≅ GF(q^m) iff p = q and n = m.

        Args:
            field1: First field structure {'p': prime, 'n': degree}
            field2: Second field structure

        Returns:
            Isomorphism result
        """
        try:
            p1 = field1.get('p') or field1.get('characteristic')
            n1 = field1.get('n') or field1.get('degree', 1)
            p2 = field2.get('p') or field2.get('characteristic')
            n2 = field2.get('n') or field2.get('degree', 1)

            if p1 is None or p2 is None:
                return {'success': False, 'error': 'Missing characteristic'}

            if not is_prime(p1):
                return {'success': False, 'error': f'p1={p1} is not prime'}
            if not is_prime(p2):
                return {'success': False, 'error': f'p2={p2} is not prime'}

            is_iso = (p1 == p2) and (n1 == n2)
            self.isomorphism_tests += 1

            reason = []
            if p1 != p2:
                reason.append(f'Different characteristics: {p1} ≠ {p2}')
            if n1 != n2:
                reason.append(f'Different degrees: {n1} ≠ {n2}')

            return {
                'success': True,
                'is_isomorphic': is_iso,
                'field1': {'p': p1, 'n': n1, 'order': p1 ** n1},
                'field2': {'p': p2, 'n': n2, 'order': p2 ** n2},
                'reason': 'Same characteristic and degree' if is_iso else '; '.join(reason),
                'method': 'order_comparison'
            }

        except Exception as e:
            return {'success': False, 'error': str(e)}

    def automorphism_group(
        self,
        p: int,
        n: int
    ) -> Dict[str, Any]:
        """
        Compute automorphism group Gal(GF(p^n)/GF(p)).

        The Galois group is cyclic of order n, generated by Frobenius φ: x → x^p.

        Args:
            p: Prime characteristic
            n: Extension degree

        Returns:
            Automorphism group structure
        """
        if not is_prime(p):
            return {'success': False, 'error': f'p={p} is not prime'}

        if n < 1:
            return {'success': False, 'error': f'n={n} must be positive'}

        try:
            # Galois group is cyclic of order n
            # Automorphisms are φ^0 = id, φ^1, φ^2, ..., φ^{n-1}
            automorphisms = []
            for k in range(n):
                auto = {
                    'power': k,
                    'name': f'φ^{k}' if k > 0 else 'id',
                    'action': f'x ↦ x^{p**k}',
                    'order': n // self._gcd(k, n) if k > 0 else 1
                }
                automorphisms.append(auto)

            self.automorphism_groups_computed += 1

            return {
                'success': True,
                'group_structure': f'Z/{n}Z',
                'order': n,
                'is_cyclic': True,
                'generator': 'φ (Frobenius: x ↦ x^p)',
                'automorphisms': automorphisms,
                'field': f'GF({p}^{n})',
                'base_field': f'GF({p})',
                'method': 'frobenius_generation'
            }

        except Exception as e:
            return {'success': False, 'error': str(e)}

    def fixed_field(
        self,
        p: int,
        n: int,
        subgroup_generators: List[int]
    ) -> Dict[str, Any]:
        """
        Compute fixed field of automorphism subgroup.

        Fix(<φ^k>) = GF(p^{gcd(k,n)}).

        Args:
            p: Prime characteristic
            n: Extension degree
            subgroup_generators: Frobenius powers generating subgroup

        Returns:
            Fixed field structure
        """
        if not is_prime(p):
            return {'success': False, 'error': f'p={p} is not prime'}

        if n < 1:
            return {'success': False, 'error': f'n={n} must be positive'}

        try:
            # Compute subgroup generated by given Frobenius powers
            # H = <φ^{k_1}, φ^{k_2}, ...> ≤ Z/nZ
            subgroup = set()
            to_process = [g % n for g in subgroup_generators]

            while to_process:
                g = to_process.pop()
                if g in subgroup:
                    continue
                subgroup.add(g)

                # Generate by adding group elements
                for h in list(subgroup):
                    new_elem = (g + h) % n
                    if new_elem not in subgroup:
                        to_process.append(new_elem)

            subgroup_order = len(subgroup)

            # By Galois correspondence, Fix(H) has degree n / |H|
            fixed_degree = n // subgroup_order

            self.fixed_fields_computed += 1

            return {
                'success': True,
                'fixed_field': f'GF({p}^{fixed_degree})',
                'fixed_degree': fixed_degree,
                'subgroup_order': subgroup_order,
                'subgroup_elements': sorted(subgroup),
                'extension_field': f'GF({p}^{n})',
                'galois_correspondence': f'H ↔ GF({p}^{fixed_degree})',
                'method': 'galois_correspondence'
            }

        except Exception as e:
            return {'success': False, 'error': str(e)}

    def orbit_under_automorphisms(
        self,
        elem: List[int],
        irred_poly: List[int],
        p: int,
        subgroup_generators: Optional[List[int]] = None
    ) -> Dict[str, Any]:
        """
        Compute orbit of element under automorphism (sub)group.

        Args:
            elem: Element coefficients
            irred_poly: Irreducible polynomial
            p: Prime characteristic
            subgroup_generators: Frobenius powers (None = full group)

        Returns:
            Orbit of element
        """
        if not is_prime(p):
            return {'success': False, 'error': f'p={p} is not prime'}

        try:
            n = len(irred_poly) - 1

            # Default: full Galois group
            if subgroup_generators is None:
                subgroup_generators = [1]  # <φ> = full group

            # Compute subgroup
            subgroup = set()
            to_process = [g % n for g in subgroup_generators]

            while to_process:
                g = to_process.pop()
                if g in subgroup:
                    continue
                subgroup.add(g)
                for h in list(subgroup):
                    new_elem = (g + h) % n
                    if new_elem not in subgroup:
                        to_process.append(new_elem)

            # Compute orbit
            orbit = []
            seen = set()

            for power in sorted(subgroup):
                image = self._apply_frobenius_power(elem, power, irred_poly, p)
                image_tuple = tuple(self._normalize(image))

                if image_tuple not in seen:
                    seen.add(image_tuple)
                    orbit.append({
                        'element': list(image_tuple),
                        'automorphism': f'φ^{power}'
                    })

            self.orbits_computed += 1

            return {
                'success': True,
                'orbit': orbit,
                'orbit_size': len(orbit),
                'stabilizer_order': len(subgroup) // len(orbit),
                'original_element': elem,
                'method': 'automorphism_action'
            }

        except Exception as e:
            return {'success': False, 'error': str(e)}

    def subfields(
        self,
        p: int,
        n: int
    ) -> Dict[str, Any]:
        """
        Enumerate all subfields of GF(p^n).

        GF(p^d) is subfield iff d | n.

        Args:
            p: Prime characteristic
            n: Extension degree

        Returns:
            List of all subfields
        """
        if not is_prime(p):
            return {'success': False, 'error': f'p={p} is not prime'}

        if n < 1:
            return {'success': False, 'error': f'n={n} must be positive'}

        try:
            divisors = self._get_divisors(n)

            subfields = []
            for d in divisors:
                subfield = {
                    'degree': d,
                    'order': p ** d,
                    'field': f'GF({p}^{d})',
                    'fixing_subgroup_order': n // d,
                    'extension_degree_over_base': d
                }
                subfields.append(subfield)

            return {
                'success': True,
                'parent_field': f'GF({p}^{n})',
                'subfields': subfields,
                'count': len(subfields),
                'lattice_structure': 'Divisor lattice of n',
                'method': 'divisibility'
            }

        except Exception as e:
            return {'success': False, 'error': str(e)}

    # ========================================
    # Helper Methods
    # ========================================

    def _gcd(self, a: int, b: int) -> int:
        """Compute gcd(a, b)."""
        while b:
            a, b = b, a % b
        return a

    def _get_divisors(self, n: int) -> List[int]:
        """Get all divisors of n."""
        divisors = []
        for i in range(1, int(n ** 0.5) + 1):
            if n % i == 0:
                divisors.append(i)
                if i != n // i:
                    divisors.append(n // i)
        return sorted(divisors)

    def _normalize(self, poly: List[int]) -> List[int]:
        """Remove trailing zeros."""
        result = list(poly)
        while result and result[-1] == 0:
            result.pop()
        return result if result else [0]

    def _apply_frobenius_power(
        self,
        elem: List[int],
        power: int,
        irred_poly: List[int],
        p: int
    ) -> List[int]:
        """Apply Frobenius power: elem -> elem^{p^power}."""
        result = list(elem)
        for _ in range(power):
            result = self._frobenius_once(result, irred_poly, p)
        return result

    def _frobenius_once(
        self,
        elem: List[int],
        irred_poly: List[int],
        p: int
    ) -> List[int]:
        """Apply Frobenius once: elem -> elem^p."""
        if not elem or all(c == 0 for c in elem):
            return [0]

        result = [1]
        base = list(elem)
        exp = p

        while exp > 0:
            if exp & 1:
                result = polynomial_mult_mod(result, base, irred_poly, p)
            base = polynomial_mult_mod(base, base, irred_poly, p)
            exp >>= 1

        return result

    # ========================================
    # Task Processing
    # ========================================

    def process(self, task_entry: Any) -> Any:
        """Process field isomorphism task."""
        self.tasks_executed += 1

        try:
            # Extract metadata
            if hasattr(task_entry, 'metadata'):
                metadata = task_entry.metadata or {}
            elif isinstance(task_entry, dict):
                metadata = task_entry
            else:
                metadata = {'operation': str(task_entry)}

            operation = metadata.get('operation', 'automorphism_group')
            p = metadata.get('p') or metadata.get('characteristic')
            n = metadata.get('n') or metadata.get('degree')
            field1 = metadata.get('field1')
            field2 = metadata.get('field2')
            elem = metadata.get('element') or metadata.get('elem')
            irred_poly = metadata.get('irred_poly')
            subgroup = metadata.get('subgroup') or metadata.get('generators')

            # Route to appropriate method
            if operation in ['isomorphic', 'are_isomorphic', 'iso']:
                result = self.are_isomorphic(field1, field2)
            elif operation in ['automorphism', 'automorphism_group', 'galois_group']:
                result = self.automorphism_group(p, n)
            elif operation in ['fixed', 'fixed_field']:
                result = self.fixed_field(p, n, subgroup)
            elif operation in ['orbit', 'orbit_under_automorphisms']:
                result = self.orbit_under_automorphisms(elem, irred_poly, p, subgroup)
            elif operation in ['subfields', 'all_subfields']:
                result = self.subfields(p, n)
            else:
                if p is not None and n is not None:
                    result = self.automorphism_group(p, n)
                else:
                    result = {'success': False, 'error': f'Unknown operation: {operation}'}

            if result.get('success', False):
                self.tasks_succeeded += 1
            else:
                self.tasks_failed += 1

            # Create blackboard entry if applicable
            if self.blackboard and hasattr(task_entry, 'conversation_id'):
                return create_entry(
                    EntryType.PARTIAL_RESULT,
                    str(result),
                    self.agent_id,
                    task_entry.conversation_id,
                    ['finite_field', 'isomorphism', 'automorphism'],
                    EntryStatus.COMPLETED if result.get('success') else EntryStatus.FAILED,
                    {'result': result}
                )

            return result

        except Exception as e:
            self.tasks_failed += 1
            logger.error(f"[{self.agent_id}] Task processing failed: {e}")
            return {'success': False, 'error': str(e)}

    # ========================================
    # BDI Interface
    # ========================================

    def update_beliefs(self):
        """PERCEIVE: Monitor blackboard for isomorphism tasks."""
        if not self.blackboard:
            return

        entries = self.blackboard.query_entries(
            tags=['isomorphism', 'automorphism', 'galois_group'],
            status=EntryStatus.PENDING
        )

        for entry in entries:
            belief_key = f'pending_iso_{entry.entry_id}'
            if not self.has_belief(belief_key):
                self.add_belief(belief_key, entry, confidence=1.0, source='blackboard')

    def deliberate(self) -> List[Intention]:
        """DELIBERATE: Create plans from beliefs."""
        new_intentions = []

        for predicate, belief in list(self.beliefs.items()):
            if not predicate.startswith('pending_iso_'):
                continue

            task = belief.content
            task_id = task.entry_id if hasattr(task, 'entry_id') else str(task)

            if any(i.metadata.get('task_id') == task_id for i in self.intentions):
                continue

            intention = Intention(
                goal=f'solve_iso_{task_id}',
                plan=['claim', 'solve', 'post'],
                priority=5,
                metadata={'task_id': task_id, 'task_entry': task}
            )
            new_intentions.append(intention)

        return new_intentions

    def execute_step(self, intention: Intention):
        """EXECUTE: Run one action from plan."""
        action = intention.get_current_action()

        if action == 'claim':
            intention.advance()
        elif action == 'solve':
            task_entry = intention.metadata.get('task_entry')
            result = self.process(task_entry)
            intention.metadata['result'] = result
            intention.advance()
        elif action == 'post':
            result = intention.metadata.get('result')
            if self.blackboard and result and hasattr(result, 'entry_type'):
                self.blackboard.post(result)
            intention.complete()

    # ========================================
    # Statistics
    # ========================================

    def get_stats(self) -> Dict[str, int]:
        """Return computation statistics."""
        return {
            'tasks_executed': self.tasks_executed,
            'tasks_succeeded': self.tasks_succeeded,
            'tasks_failed': self.tasks_failed,
            'isomorphism_tests': self.isomorphism_tests,
            'automorphism_groups_computed': self.automorphism_groups_computed,
            'fixed_fields_computed': self.fixed_fields_computed,
            'orbits_computed': self.orbits_computed,
        }
