# Copyright 2025 Michael Maillet, Damien Davison, and Sacha Davison
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Phase 6 System: The Mathematical Discovery Engine (Simplified)
"""
import time
import logging
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Callable
from datetime import datetime
from enum import Enum

logger = logging.getLogger('symbo_agentic_reasoners.discovery.phase6_system')

class SystemStatus(Enum):
    STOPPED = 'stopped'
    STARTING = 'starting'
    RUNNING = 'running'
    PAUSED = 'paused'
    ERROR = 'error'

# Import from discovery submodules
from symbo_agentic_reasoners.discovery.conjecture import (
    SyntheticDataGenerator, PatternRecognizer, ConjectureFormalizer,
    CandidateConjecture, ConjectureStatus
)
from symbo_agentic_reasoners.discovery.deep_search import (
    PolicyNetwork, CriticNetwork, SearchTreeManager, SymPyProver,
    ProofState, SearchResult, ProverEngine
)
from symbo_agentic_reasoners.discovery.algorithm import (
    CodeEvolutionaryProposer, SandboxEvaluator, HeuristicDistiller,
    ProblemSpecification, CodeCandidate
)
from symbo_agentic_reasoners.discovery.undecidability import (
    DecidabilityChecker, DecidabilityClass, InteractiveGuidanceLiaison, ProofStateSummary
)
from symbo_agentic_reasoners.discovery.formal import (
    AutoFormalizationPipeline, VectorDatabaseUpdater, FormalizedDiscovery
)


@dataclass
class DiscoveryCycleResult:
    """
    Results from a single discovery cycle.

    A discovery cycle represents one complete iteration through Phase 6's
    five-team discovery pipeline:
    1. Conjecture Generation (Team 1)
    2. Deep Search Proving (Team 2)
    3. Algorithm Discovery (Team 3)
    4. Undecidability Navigation (Team 4)
    5. Formal Knowledge Integration (Team 5)

    Attributes:
        cycle_id: Unique identifier for this cycle
        theorems_generated: Number of conjectures generated by Team 1
        conjectures_filtered: Number passing initial validation
        proofs_attempted: Number of proof searches initiated by Team 2
        proofs_succeeded: Number of successful proofs found
        discoveries_integrated: Number formalized by Team 5
        time_elapsed_ms: Total cycle time in milliseconds
        errors: List of error messages encountered
    """
    cycle_id: str
    theorems_generated: int
    conjectures_filtered: int
    proofs_attempted: int
    proofs_succeeded: int
    discoveries_integrated: int
    time_elapsed_ms: float
    errors: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert cycle results to dictionary format.

        Returns:
            Dict[str, Any]: Results dictionary with computed success rate

        Example:
            >>> result = DiscoveryCycleResult(
            ...     cycle_id="cycle_001",
            ...     theorems_generated=10,
            ...     conjectures_filtered=8,
            ...     proofs_attempted=8,
            ...     proofs_succeeded=3,
            ...     discoveries_integrated=3,
            ...     time_elapsed_ms=1500.0
            ... )
            >>> data = result.to_dict()
            >>> data['success_rate']
            37.5
            >>> data['cycle_id']
            'cycle_001'
        """
        return {
            'cycle_id': self.cycle_id,
            'theorems_generated': self.theorems_generated,
            'conjectures_filtered': self.conjectures_filtered,
            'proofs_attempted': self.proofs_attempted,
            'proofs_succeeded': self.proofs_succeeded,
            'discoveries_integrated': self.discoveries_integrated,
            'time_elapsed_ms': self.time_elapsed_ms,
            'success_rate': self.proofs_succeeded / max(1, self.proofs_attempted) * 100,
            'errors': self.errors
        }


class Phase6System:
    """
    Phase 6: The Mathematical Discovery Engine

    The top-level orchestrator for autonomous mathematical discovery,
    coordinating five specialized teams to generate, prove, and integrate
    novel mathematical knowledge.

    Five-Team Architecture:
    ----------------------
    1. Conjecture Generation Team
       - SyntheticDataGenerator: Creates training data
       - PatternRecognizer: Detects patterns in data
       - ConjectureFormalizer: Converts patterns to formal conjectures

    2. Deep Search Proving Team
       - PolicyNetwork: Learns proof search strategies
       - CriticNetwork: Evaluates proof states
       - SearchTreeManager: Orchestrates proof search
       - ProverEngine: Executes proof tactics

    3. Algorithm Discovery Team (FunSearch)
       - CodeEvolutionaryProposer: Generates code candidates
       - SandboxEvaluator: Tests candidates safely
       - HeuristicDistiller: Extracts reusable patterns

    4. Undecidability Navigation Team
       - DecidabilityChecker: Classifies problem decidability
       - InteractiveGuidanceLiaison: Requests human guidance

    5. Formal Knowledge Integration Team
       - AutoFormalizationPipeline: Converts to OMDoc/Lean4
       - VectorDatabaseUpdater: Indexes for RAG retrieval

    Integration with Phase System:
    -----------------------------
    - Phase 0: Uses OMDoc schema and infrastructure
    - Phase 1: Verification core validates discoveries
    - Phase 2: Supervisors use discoveries as primitives
    - Phase 5: Builds on curiosity/imagination engines

    Reference:
        Phase 6 must engineer the capacity for novel mathematical discovery.docx
    """

    def __init__(
        self,
        phase5_system=None,
        verification_core=None,
        knowledge_base=None,
        guidance_callback: Callable = None,
        synthetic_data_generator: Optional[SyntheticDataGenerator] = None,
        pattern_recognizer: Optional[PatternRecognizer] = None,
        conjecture_formalizer: Optional[ConjectureFormalizer] = None,
        policy_network: Optional[PolicyNetwork] = None,
        critic_network: Optional[CriticNetwork] = None,
        prover_engine: Optional[Any] = None,
        search_tree_manager: Optional[SearchTreeManager] = None,
        code_evolutionary_proposer: Optional[CodeEvolutionaryProposer] = None,
        sandbox_evaluator: Optional[SandboxEvaluator] = None,
        heuristic_distiller: Optional[HeuristicDistiller] = None,
        decidability_checker: Optional[DecidabilityChecker] = None,
        interactive_guidance_liaison: Optional[InteractiveGuidanceLiaison] = None,
        auto_formalization_pipeline: Optional[AutoFormalizationPipeline] = None,
        vector_database_updater: Optional[VectorDatabaseUpdater] = None
    ):
        """
        Initialize the Phase 6 Mathematical Discovery Engine.

        Args:
            phase5_system: Phase 5 curiosity/imagination engine
            verification_core: Phase 1 verification core
            knowledge_base: Mathematical knowledge base
            guidance_callback: Callback for human guidance requests
            synthetic_data_generator: Team 1 data generator
            pattern_recognizer: Team 1 pattern detector
            conjecture_formalizer: Team 1 conjecture formalizer
            policy_network: Team 2 policy network
            critic_network: Team 2 critic network
            prover_engine: Team 2 proof engine (e.g., SymPyProver)
            search_tree_manager: Team 2 search orchestrator
            code_evolutionary_proposer: Team 3 code generator
            sandbox_evaluator: Team 3 safety evaluator
            heuristic_distiller: Team 3 pattern extractor
            decidability_checker: Team 4 decidability classifier
            interactive_guidance_liaison: Team 4 human interface
            auto_formalization_pipeline: Team 5 formalization pipeline
            vector_database_updater: Team 5 RAG database

        Example:
            >>> system = Phase6System()
            >>> system.status
            'stopped'
            >>> system.start()
            >>> system.status
            'running'
        """
        self.phase5 = phase5_system
        self.verification_core = verification_core
        self.knowledge_base = knowledge_base
        self._status = SystemStatus.STOPPED
        self.started_at: Optional[datetime] = None
        self.cycle_count = 0

        # Team 1: Conjecture Generation
        self.synthetic_data_generator = synthetic_data_generator or SyntheticDataGenerator()
        self.pattern_recognizer = pattern_recognizer or PatternRecognizer(knowledge_base=knowledge_base)
        self.conjecture_formalizer = conjecture_formalizer or ConjectureFormalizer()

        # Team 2: Deep Search
        self.policy_network = policy_network or PolicyNetwork()
        self.critic_network = critic_network or CriticNetwork()
        self.prover_engine = prover_engine or SymPyProver()

        if search_tree_manager:
            self.search_tree_manager = search_tree_manager
        else:
            self.search_tree_manager = SearchTreeManager(
                policy_network=self.policy_network,
                critic_network=self.critic_network,
                prover_engine=self.prover_engine
            )

        # Team 3: Algorithm Discovery
        self.code_evolutionary_proposer = code_evolutionary_proposer or CodeEvolutionaryProposer()
        self.sandbox_evaluator = sandbox_evaluator or SandboxEvaluator()
        self.heuristic_distiller = heuristic_distiller or HeuristicDistiller()

        # Team 4: Undecidability Navigator
        self.decidability_checker = decidability_checker or DecidabilityChecker()
        self.interactive_guidance_liaison = interactive_guidance_liaison or InteractiveGuidanceLiaison(
            notification_callback=guidance_callback
        )

        # Team 5: Formal Knowledge Integration
        self.auto_formalization_pipeline = auto_formalization_pipeline or AutoFormalizationPipeline(
            verification_core=verification_core
        )
        self.vector_database_updater = vector_database_updater or VectorDatabaseUpdater()

        self.stats = {
            'discovery_cycles': 0,
            'total_theorems_generated': 0,
            'total_proofs_found': 0,
            'algorithms_discovered': 0,
            'discoveries_integrated': 0,
        }

    @property
    def status(self) -> str:
        """
        Get current system status.

        Returns:
            str: Status value ('stopped', 'starting', 'running', 'paused', 'error')

        Example:
            >>> system = Phase6System()
            >>> system.status
            'stopped'
            >>> system.start()
            >>> system.status
            'running'
        """
        return self._status.value

    def start(self):
        """
        Start the discovery engine.

        Transitions the system from STOPPED to RUNNING, enabling all five
        teams to begin autonomous discovery cycles.

        Example:
            >>> system = Phase6System()
            >>> system.start()
            >>> system.status
            'running'
            >>> system.started_at is not None
            True
        """
        if self._status == SystemStatus.RUNNING:
            return
        self._status = SystemStatus.STARTING
        self.started_at = datetime.now()
        self._status = SystemStatus.RUNNING

    def shutdown(self):
        """
        Shut down the discovery engine.

        Stops all discovery cycles and transitions to STOPPED state.
        This does not clear statistics or formalized discoveries.

        Example:
            >>> system = Phase6System()
            >>> system.start()
            >>> system.shutdown()
            >>> system.status
            'stopped'
        """
        self._status = SystemStatus.STOPPED

    def health_check(self) -> Dict[str, bool]:
        """
        Check health of all five discovery teams.

        Queries each team's components to verify operational status.
        This is useful for monitoring and debugging the discovery pipeline.

        Returns:
            Dict[str, bool]: Health status for each team and overall system

        Example:
            >>> system = Phase6System()
            >>> system.start()
            >>> health = system.health_check()
            >>> health['overall']
            True
            >>> health['conjecture_generation']
            True
            >>> health['deep_search']
            True
            >>> health['algorithm_discovery']
            True
            >>> health['undecidability_navigator']
            True
            >>> health['formal_knowledge_integration']
            True
        """
        # Call all component health checks including prover
        prover_health = self.prover_engine.health_check() if hasattr(self.prover_engine, 'health_check') else True
        return {
            'overall': self._status == SystemStatus.RUNNING,
            'conjecture_generation': self.synthetic_data_generator.health_check(),
            'deep_search': self.policy_network.health_check() and prover_health,
            'algorithm_discovery': self.code_evolutionary_proposer.health_check(),
            'undecidability_navigator': self.decidability_checker.health_check(),
            'formal_knowledge_integration': self.auto_formalization_pipeline.health_check()
        }

    def get_statistics(self) -> Dict[str, Any]:
        """
        Get discovery system statistics.

        Returns comprehensive metrics across all discovery cycles,
        including theorems generated, proofs found, algorithms discovered,
        and discoveries integrated.

        Returns:
            Dict[str, Any]: System statistics including:
                - status: Current system status
                - discovery_cycles: Total cycles completed
                - total_theorems_generated: Conjectures generated
                - total_proofs_found: Successful proofs
                - algorithms_discovered: Novel algorithms found
                - discoveries_integrated: Formalized discoveries

        Example:
            >>> system = Phase6System()
            >>> stats = system.get_statistics()
            >>> stats['system']['status']
            'stopped'
            >>> stats['system']['discovery_cycles']
            0
            >>> stats['system']['total_theorems_generated']
            0
        """
        return {'system': {'status': self.status, **self.stats}}
