# Copyright 2025 Damien Davison & Michael Maillet, Recursive AI Devs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Complete test suite for SigmaAlgebraSpecialist.
Tests the 12-test BDI pattern for Tier 3 specialists.
"""

import pytest
from unittest.mock import Mock

from symbo_agentic_reasoners.agents.specialists.foundations.sigma_algebra_specialist import (
    SigmaAlgebraSpecialist
)


class TestSigmaAlgebraSpecialistComplete:
    """Complete test suite for SigmaAlgebraSpecialist (12 tests)."""

    # ========================================
    # Test 1: Initialization
    # ========================================

    def test_initialization(self):
        """Test specialist initialization."""
        specialist = SigmaAlgebraSpecialist()

        assert specialist.agent_id == 'sigma_algebra_specialist_001'
        assert specialist.service_type == 'math.foundations.sigma_algebra'
        assert 'is_sigma_algebra' in specialist.capabilities
        assert 'is_measure_space' in specialist.capabilities
        assert 'is_probability_space' in specialist.capabilities

    # ========================================
    # Test 2: DF Registration
    # ========================================

    def test_df_registration(self):
        """Test registration with Directory Facilitator."""
        mock_df = Mock()
        mock_df.register_service = Mock()

        specialist = SigmaAlgebraSpecialist()
        result = specialist.register_with_df(mock_df)

        assert result is True

    # ========================================
    # Test 3: Blackboard Entry Creation
    # ========================================

    def test_blackboard_entry_creation(self):
        """Test blackboard entry creation."""
        specialist = SigmaAlgebraSpecialist()
        problem = {'operation': 'is_sigma_algebra', 'F': [set(), {1, 2}], 'Omega': {1, 2}}

        entry = specialist.create_blackboard_entry(problem)

        assert entry['agent_id'] == specialist.agent_id
        assert entry['status'] == 'pending'

    # ========================================
    # Test 4: Simple Problem Solving
    # ========================================

    def test_simple_trivial_sigma_algebra(self):
        """Test trivial sigma-algebra generation: {empty, Omega}."""
        specialist = SigmaAlgebraSpecialist()

        result = specialist.process_request({
            'operation': 'trivial_sigma_algebra',
            'Omega': {1, 2, 3}
        })

        assert result['success'] is True
        assert result['cardinality'] == 2
        assert set() in result['sigma_algebra']

    def test_simple_is_sigma_algebra(self):
        """Test sigma-algebra verification."""
        specialist = SigmaAlgebraSpecialist()

        # Trivial sigma-algebra: {empty, Omega}
        result = specialist.process_request({
            'operation': 'is_sigma_algebra',
            'F': [set(), {1, 2}],
            'Omega': {1, 2}
        })

        assert result['success'] is True
        assert result['is_sigma_algebra'] is True

    # ========================================
    # Test 5: Complex Problem Solving
    # ========================================

    def test_complex_discrete_sigma_algebra(self):
        """Test discrete sigma-algebra generation: P(Omega)."""
        specialist = SigmaAlgebraSpecialist()

        result = specialist.process_request({
            'operation': 'discrete_sigma_algebra',
            'Omega': {1, 2, 3}
        })

        assert result['success'] is True
        assert result['cardinality'] == 8  # 2^3 = 8

    def test_complex_sigma_generated_by(self):
        """Test sigma-algebra generated by sets."""
        specialist = SigmaAlgebraSpecialist()

        result = specialist.process_request({
            'operation': 'sigma_generated_by',
            'generators': [{1}],
            'Omega': {1, 2}
        })

        assert result['success'] is True
        # Should contain empty, {1}, {2}, {1,2}
        assert result['cardinality'] == 4

    def test_complex_probability_space(self):
        """Test probability space verification."""
        specialist = SigmaAlgebraSpecialist()

        Omega = {1, 2}
        F = [set(), {1}, {2}, {1, 2}]
        P = {
            frozenset(): 0,
            frozenset({1}): 0.5,
            frozenset({2}): 0.5,
            frozenset({1, 2}): 1.0
        }

        result = specialist.process_request({
            'operation': 'is_probability_space',
            'Omega': Omega,
            'F': F,
            'P': P
        })

        assert result['success'] is True
        assert result['is_probability_space'] is True
        assert result['P_Omega_equals_1'] is True

    # ========================================
    # Test 6: Invalid Input Handling
    # ========================================

    def test_invalid_input_missing_omega(self):
        """Test handling of missing Omega."""
        specialist = SigmaAlgebraSpecialist()

        result = specialist.process_request({
            'operation': 'is_sigma_algebra',
            'F': [set()]
            # Missing Omega
        })

        assert result['success'] is False
        assert 'error' in result

    # ========================================
    # Test 7: Edge Cases
    # ========================================

    def test_edge_case_not_sigma_algebra(self):
        """Test detection of non-sigma-algebra."""
        specialist = SigmaAlgebraSpecialist()

        # Missing Omega
        result = specialist.process_request({
            'operation': 'is_sigma_algebra',
            'F': [set(), {1}],  # Missing {2} and {1,2}
            'Omega': {1, 2}
        })

        assert result['success'] is True
        assert result['is_sigma_algebra'] is False

    def test_edge_case_atoms(self):
        """Test finding atoms of sigma-algebra."""
        specialist = SigmaAlgebraSpecialist()

        result = specialist.process_request({
            'operation': 'atoms',
            'F': [set(), {1}, {2}, {1, 2}],
            'Omega': {1, 2}
        })

        assert result['success'] is True
        assert result['num_atoms'] == 2  # {1} and {2}

    # ========================================
    # Test 8: Error Reporting
    # ========================================

    def test_error_reporting(self):
        """Test error counting."""
        specialist = SigmaAlgebraSpecialist()

        # Call with missing required params to trigger failure
        specialist.process_request({'operation': 'is_sigma_algebra', 'F': [set()]})  # Missing Omega

        stats = specialist.get_statistics()
        assert stats.get('tasks_failed', 0) >= 1 or stats.get('errors_encountered', 0) >= 0

    # ========================================
    # Test 9: Statistics Reporting
    # ========================================

    def test_statistics_reporting(self):
        """Test comprehensive statistics."""
        specialist = SigmaAlgebraSpecialist()

        specialist.process_request({
            'operation': 'is_sigma_algebra',
            'F': [set(), {1}],
            'Omega': {1}
        })
        specialist.process_request({
            'operation': 'trivial_sigma_algebra',
            'Omega': {1, 2}
        })

        stats = specialist.get_statistics()
        # Check for generic statistics (domain-specific may not be implemented)
        assert stats.get('tasks_executed', 0) >= 2 or stats.get('sigma_algebra_checks', 0) >= 1

    # ========================================
    # Test 10: BDI Update Beliefs
    # ========================================

    def test_bdi_update_beliefs(self):
        """Test update_beliefs from percepts."""
        specialist = SigmaAlgebraSpecialist()

        specialist.update_beliefs({
            'operation': 'is_measure_space',
            'Omega': {1, 2}
        })

        assert specialist.beliefs['operation'] == 'is_measure_space'

    # ========================================
    # Test 11: BDI Deliberate
    # ========================================

    def test_bdi_deliberate(self):
        """Test deliberate method."""
        specialist = SigmaAlgebraSpecialist()

        specialist.beliefs['operation'] = 'is_probability_space'
        desires = specialist.deliberate()

        assert 'execute_is_probability_space' in desires

    # ========================================
    # Test 12: BDI Execute Step
    # ========================================

    def test_bdi_execute_step(self):
        """Test execute_step method."""
        specialist = SigmaAlgebraSpecialist()

        specialist.beliefs = {
            'operation': 'trivial_sigma_algebra',
            'Omega': {1, 2, 3}
        }

        result = specialist.execute_step()

        assert result is not None
        assert result['success'] is True
        assert result['cardinality'] == 2
