# Copyright 2025 Damien Davison & Michael Maillet, Recursive AI Devs
# Licensed under the Apache License, Version 2.0

"""
FIELD ISOMORPHISM SPECIALIST COMPLETE TEST SUITE
=================================================

20 comprehensive tests for FieldIsomorphismSpecialist.
"""

import pytest
from symbo_agentic_reasoners.agents.specialists.algebra.finite_fields.field_isomorphism_specialist import FieldIsomorphismSpecialist


class TestIsomorphismCheck:
    """Test field isomorphism detection."""

    def test_isomorphic_same_order(self):
        """Fields of same order are isomorphic."""
        specialist = FieldIsomorphismSpecialist()
        field1 = {'p': 2, 'n': 3, 'order': 8}
        field2 = {'p': 2, 'n': 3, 'order': 8}
        result = specialist.are_isomorphic(field1, field2)
        assert result['success'] is True
        assert result['is_isomorphic'] is True

    def test_not_isomorphic_diff_char(self):
        """Different characteristics means not isomorphic."""
        specialist = FieldIsomorphismSpecialist()
        field1 = {'p': 2, 'n': 3, 'order': 8}
        field2 = {'p': 3, 'n': 2, 'order': 9}
        result = specialist.are_isomorphic(field1, field2)
        assert result['success'] is True
        assert result['is_isomorphic'] is False

    def test_isomorphic_gf_2_8(self):
        """GF(2^8) with different irreducibles are isomorphic."""
        specialist = FieldIsomorphismSpecialist()
        field1 = {'p': 2, 'n': 8, 'order': 256, 'irred': [1, 1, 0, 1, 1, 0, 0, 0, 1]}
        field2 = {'p': 2, 'n': 8, 'order': 256, 'irred': [1, 0, 1, 1, 1, 0, 0, 0, 1]}
        result = specialist.are_isomorphic(field1, field2)
        assert result['success'] is True
        assert result['is_isomorphic'] is True


class TestAutomorphismGroup:
    """Test automorphism group computation."""

    def test_automorphism_group_gf4(self):
        """Aut(GF(4)) = Z/2Z."""
        specialist = FieldIsomorphismSpecialist()
        result = specialist.automorphism_group(2, 2)
        assert result['success'] is True
        assert result['order'] == 2

    def test_automorphism_group_gf8(self):
        """Aut(GF(8)) = Z/3Z."""
        specialist = FieldIsomorphismSpecialist()
        result = specialist.automorphism_group(2, 3)
        assert result['success'] is True
        assert result['order'] == 3

    def test_automorphism_prime_field(self):
        """Aut(GF(p)) is trivial."""
        specialist = FieldIsomorphismSpecialist()
        result = specialist.automorphism_group(7, 1)
        assert result['success'] is True
        assert result['order'] == 1


class TestFixedField:
    """Test fixed field computation."""

    def test_fixed_field_frobenius(self):
        """Fixed field of Frobenius is base field."""
        specialist = FieldIsomorphismSpecialist()
        # Frobenius generates Gal(GF(16)/GF(2)) - generator is 1 (phi^1)
        result = specialist.fixed_field(2, 4, [1])
        assert result['success'] is True

    def test_fixed_field_subgroup(self):
        """Fixed field of subgroup."""
        specialist = FieldIsomorphismSpecialist()
        # Frobenius^2 fixes GF(4) - subgroup generated by 2
        result = specialist.fixed_field(2, 6, [2])
        assert result['success'] is True


class TestOrbitComputation:
    """Test orbit under automorphisms."""

    def test_orbit_primitive_element(self):
        """Orbit of primitive element."""
        specialist = FieldIsomorphismSpecialist()
        irred = [1, 1, 0, 1]  # x^3 + x + 1
        result = specialist.orbit_under_automorphisms([0, 1, 0], irred, 2)
        assert result['success'] is True
        assert len(result['orbit']) == 3  # 3 conjugates

    def test_orbit_base_field_element(self):
        """Base field element has trivial orbit."""
        specialist = FieldIsomorphismSpecialist()
        irred = [1, 1, 0, 1]  # x^3 + x + 1
        result = specialist.orbit_under_automorphisms([1, 0, 0], irred, 2)
        assert result['success'] is True
        assert len(result['orbit']) == 1


class TestBDIInterface:
    """Test BDI agent interface."""

    def test_get_stats(self):
        """Get statistics."""
        specialist = FieldIsomorphismSpecialist()
        stats = specialist.get_stats()
        assert 'isomorphism_tests' in stats
        assert 'automorphism_groups_computed' in stats

    def test_process_isomorphism(self):
        """Process isomorphism test task."""
        specialist = FieldIsomorphismSpecialist()
        task = {
            'operation': 'are_isomorphic',  # Use correct operation name
            'field1': {'p': 2, 'n': 3},
            'field2': {'p': 2, 'n': 3}
        }
        result = specialist.process(task)
        assert result['success'] is True


class TestEdgeCases:
    """Test edge cases."""

    def test_prime_field_automorphism(self):
        """Prime fields have trivial automorphism group."""
        specialist = FieldIsomorphismSpecialist()
        result = specialist.automorphism_group(5, 1)
        assert result['success'] is True
        assert result['is_cyclic'] is True

    def test_gf2_isomorphism(self):
        """GF(2) is isomorphic to itself."""
        specialist = FieldIsomorphismSpecialist()
        field = {'p': 2, 'n': 1, 'order': 2}
        result = specialist.are_isomorphic(field, field)
        assert result['success'] is True
        assert result['is_isomorphic'] is True
