# Copyright 2025 Damien Davison & Michael Maillet, Recursive AI Devs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Phase 6: The Mathematical Discovery Engine
============================================

Complete implementation of the 13-agent Discovery Engine architecture.
Transitions the system from Problem Solver to Discovery Engine.

Teams Implemented:
1. Conjecture Generation Team (3 agents) - "The Theorist"
2. Deep Search Team (3 agents) - "The Explorer"  
3. Algorithm Discovery Unit (3 agents) - "FunSearch Pattern"
4. Undecidability Navigator (2 agents) - "Boundary Watcher"
5. Formal Knowledge Integration (2 agents) - "The Archivist"

Reference Documentation:
- Phase 6 represents the transition from a Problem Solving Engine.docx
- Phase 6 must engineer the capacity for novel mathematical discovery.docx
- phases_0-6_for_the_Autonomous_Mathematical_Discovery_Engine.docx
- architectural_roadmap.docx

Author: Phase 6 Discovery Engine Module
Compatible with: Phase 5 infrastructure (ThoughtTraceHarvester, DistillationPipeline)
"""

import sympy as sp
import numpy as np
import torch
import torch.nn as nn
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Generator, Tuple, Callable, Set, Any
from enum import Enum
from datetime import datetime
from abc import ABC, abstractmethod
import random
import hashlib
import json
import subprocess
import tempfile
import time
import uuid


# =============================================================================
# SECTION 1: CONJECTURE GENERATION TEAM ("The Theorist")
# =============================================================================

class ConjectureStatus(Enum):
    """Status of a conjecture through the discovery pipeline"""
    GENERATED = 'generated'      # Created by Synthetic Data Generator
    FILTERED = 'filtered'        # Passed Pattern Recognizer
    FORMALIZED = 'formalized'    # Converted to formal representation
    SUBMITTED = 'submitted'      # Sent to Deep Search Team
    PROVEN = 'proven'            # Successfully proven
    REFUTED = 'refuted'          # Counter-example found
    TIMEOUT = 'timeout'          # Search exhausted resources


@dataclass
class SyntheticTheorem:
    """
    A theorem generated by the Synthetic Data Generator.
    
    Based on AlphaGeometry paradigm: randomly sample premises
    and derive conclusions using symbolic engines.
    """
    theorem_id: str
    premises: List[sp.Expr]
    conclusion: sp.Expr
    derivation_steps: List[str]
    domain: str  # 'algebra', 'geometry', 'number_theory', 'analysis'
    complexity_score: float
    novelty_score: float = 0.0
    generation_timestamp: datetime = field(default_factory=datetime.now)
    
    def to_natural_language(self) -> str:
        """Convert to human-readable statement"""
        premises_str = " AND ".join([str(p) for p in self.premises])
        return f"IF {premises_str} THEN {self.conclusion}"
    
    def compute_hash(self) -> str:
        """Deterministic hash for deduplication"""
        content = f"{self.premises}|{self.conclusion}"
        return hashlib.md5(content.encode()).hexdigest()


@dataclass 
class CandidateConjecture:
    """
    A conjecture that has passed the Pattern Recognizer's filters.
    Ready for formalization and proof attempts.
    """
    conjecture_id: str
    source_theorem: SyntheticTheorem
    interestingness_score: float
    novelty_score: float
    cross_domain_applicability: List[str]
    status: ConjectureStatus = ConjectureStatus.FILTERED
    
    # Formalization outputs (populated by Conjecture Formalizer)
    lean4_statement: Optional[str] = None
    omdoc_representation: Optional[str] = None
    sympy_form: Optional[sp.Expr] = None


class SyntheticDataGenerator:
    """
    Agent 1.1: The Dreamer
    
    Based on AlphaGeometry paradigm, continuously generates random 
    geometric/algebraic premises and derives conclusions using Phase 2 
    symbolic engines.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 1
    """
    
    def __init__(self, symbolic_engine=None, df_client=None):
        self.symbolic_engine = symbolic_engine
        self.df = df_client  # Directory Facilitator
        self.theorem_count = 0
        
        # Define symbol pools for different domains
        self.algebra_symbols = sp.symbols('x y z a b c n m k')
        self.geometry_symbols = sp.symbols('A B C D P Q R theta phi')
        self.analysis_symbols = sp.symbols('f g h epsilon delta')
        
        # Template operations for premise generation
        self.binary_ops = [
            lambda a, b: a + b,
            lambda a, b: a * b,
            lambda a, b: a - b,
            lambda a, b: a ** b,
            lambda a, b: sp.Eq(a, b),
            lambda a, b: a > b,
            lambda a, b: a < b,
        ]
        
        self.unary_ops = [
            lambda a: a ** 2,
            lambda a: sp.sqrt(a),
            lambda a: sp.sin(a),
            lambda a: sp.cos(a),
            lambda a: sp.exp(a),
            lambda a: sp.log(a),
            lambda a: sp.diff(a, sp.Symbol('x')) if a.has(sp.Symbol('x')) else a,
        ]
    
    def generate_stream(self, batch_size: int = 1000) -> Generator[SyntheticTheorem, None, None]:
        """
        Generate synthetic theorems continuously.
        
        Yields theorems one at a time for memory efficiency.
        """
        while True:
            batch = [self._generate_single() for _ in range(batch_size)]
            valid_theorems = [t for t in batch if t is not None]
            yield from valid_theorems
    
    def _generate_single(self) -> Optional[SyntheticTheorem]:
        """Generate a single synthetic theorem"""
        try:
            domain = random.choice(['algebra', 'geometry', 'number_theory', 'analysis'])
            
            if domain == 'algebra':
                return self._generate_algebra_theorem()
            elif domain == 'geometry':
                return self._generate_geometry_theorem()
            elif domain == 'number_theory':
                return self._generate_number_theory_theorem()
            else:
                return self._generate_analysis_theorem()
                
        except Exception as e:
            # Silent failure for invalid generations
            return None
    
    def _generate_algebra_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate algebraic identity or relation"""
        x, y, z, a, b, c = sp.symbols('x y z a b c')
        
        # Random polynomial construction
        degree = random.randint(1, 3)
        terms = random.randint(2, 4)
        
        # Build random polynomial
        poly = sum(
            random.randint(-5, 5) * x**random.randint(0, degree) * y**random.randint(0, degree)
            for _ in range(terms)
        )
        
        # Generate premise (e.g., polynomial = 0)
        premises = [sp.Eq(poly, 0)]
        
        # Try to derive a conclusion
        try:
            solutions = sp.solve(poly, x)
            if solutions:
                conclusion = sp.Eq(x, solutions[0])
            else:
                # Factor the polynomial as conclusion
                factored = sp.factor(poly)
                conclusion = sp.Eq(poly, factored)
        except:
            return None
        
        self.theorem_count += 1
        
        return SyntheticTheorem(
            theorem_id=f"synth_alg_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=["solve", "simplify"],
            domain="algebra",
            complexity_score=self._compute_complexity(premises, conclusion)
        )
    
    def _generate_geometry_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate geometric relation (simplified version)"""
        a, b, c, theta = sp.symbols('a b c theta', positive=True, real=True)
        
        # Generate triangle-related theorems
        template = random.choice(['pythagorean', 'law_of_cosines', 'area'])
        
        if template == 'pythagorean':
            premises = [sp.Eq(c**2, a**2 + b**2)]
            conclusion = sp.Eq(sp.sqrt(a**2 + b**2), c)
        elif template == 'law_of_cosines':
            premises = [sp.Eq(c**2, a**2 + b**2 - 2*a*b*sp.cos(theta))]
            conclusion = sp.Eq(sp.cos(theta), (a**2 + b**2 - c**2)/(2*a*b))
        else:
            # Heron's formula related
            s = (a + b + c) / 2
            area = sp.sqrt(s * (s-a) * (s-b) * (s-c))
            premises = [sp.Gt(a + b, c), sp.Gt(b + c, a), sp.Gt(a + c, b)]
            conclusion = sp.Eq(sp.Symbol('Area'), area)
        
        self.theorem_count += 1
        
        return SyntheticTheorem(
            theorem_id=f"synth_geo_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=["geometric_construction", "algebraic_manipulation"],
            domain="geometry",
            complexity_score=self._compute_complexity(premises, conclusion)
        )
    
    def _generate_number_theory_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate number-theoretic relation"""
        n, m, p, k = sp.symbols('n m p k', integer=True, positive=True)
        
        template = random.choice(['divisibility', 'modular', 'sum_formula'])
        
        if template == 'divisibility':
            # Generate divisibility theorem
            base = random.randint(2, 10)
            power = random.randint(1, 3)
            premises = [sp.Eq(n % base, 0)]
            conclusion = sp.Eq((n**power) % base, 0)
        elif template == 'modular':
            # Fermat's little theorem variant
            premises = [sp.Eq(sp.gcd(n, p), 1)]
            conclusion = sp.Eq((n**(p-1)) % p, 1)
        else:
            # Sum formulas
            premises = [sp.Gt(n, 0)]
            sum_expr = sp.Sum(k, (k, 1, n)).doit()
            conclusion = sp.Eq(sum_expr, n*(n+1)/2)
        
        self.theorem_count += 1
        
        return SyntheticTheorem(
            theorem_id=f"synth_nt_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=["number_theoretic_analysis"],
            domain="number_theory",
            complexity_score=self._compute_complexity(premises, conclusion)
        )
    
    def _generate_analysis_theorem(self) -> Optional[SyntheticTheorem]:
        """Generate calculus/analysis theorem"""
        x, a, n = sp.symbols('x a n')
        
        template = random.choice(['derivative', 'integral', 'series'])
        
        if template == 'derivative':
            # Generate derivative identity
            f = random.choice([
                sp.sin(x), sp.cos(x), sp.exp(x), sp.log(x),
                x**n, sp.sin(x)**2, sp.exp(-x**2)
            ])
            premises = []
            conclusion = sp.Eq(sp.Derivative(f, x), sp.diff(f, x))
        elif template == 'integral':
            # Integration by parts pattern
            u = sp.exp(x)
            dv = sp.sin(x)
            premises = []
            conclusion = sp.Eq(
                sp.Integral(u * dv, x),
                u * sp.integrate(dv, x) - sp.Integral(sp.diff(u, x) * sp.integrate(dv, x), x)
            )
        else:
            # Taylor series
            f = sp.exp(x)
            premises = []
            taylor = sum(x**k / sp.factorial(k) for k in range(5))
            conclusion = sp.Eq(sp.series(f, x, 0, 5).removeO(), taylor)
        
        self.theorem_count += 1
        
        return SyntheticTheorem(
            theorem_id=f"synth_ana_{self.theorem_count}",
            premises=premises,
            conclusion=conclusion,
            derivation_steps=["calculus_rule_application"],
            domain="analysis",
            complexity_score=self._compute_complexity(premises, conclusion)
        )
    
    def _compute_complexity(self, premises: List[sp.Expr], conclusion: sp.Expr) -> float:
        """Compute complexity score for a theorem"""
        # Count total symbols and operations
        total_ops = 0
        for expr in premises + [conclusion]:
            total_ops += len(str(expr))
        
        # Normalize to 0-1 range
        return min(1.0, total_ops / 200)


class PatternRecognizer:
    """
    Agent 1.2: The Filter
    
    Sifts through millions of synthetic theorems, filtering out trivial
    tautologies and identifying "interesting" non-trivial relationships.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 1
    """
    
    def __init__(self, knowledge_base=None):
        self.knowledge_base = knowledge_base
        self.seen_hashes: Set[str] = set()
        self.pattern_counts: Dict[str, int] = {}
        
    def filter_stream(
        self, 
        theorem_stream: Generator[SyntheticTheorem, None, None],
        batch_size: int = 100
    ) -> Generator[CandidateConjecture, None, None]:
        """
        Filter theorems and yield candidate conjectures.
        """
        batch = []
        for theorem in theorem_stream:
            batch.append(theorem)
            if len(batch) >= batch_size:
                candidates = self._process_batch(batch)
                yield from candidates
                batch = []
    
    def _process_batch(self, theorems: List[SyntheticTheorem]) -> List[CandidateConjecture]:
        """Process a batch of theorems and return interesting candidates"""
        candidates = []
        
        for theorem in theorems:
            if self._is_interesting(theorem):
                candidate = self._elevate_to_candidate(theorem)
                if candidate:
                    candidates.append(candidate)
        
        return candidates
    
    def _is_interesting(self, theorem: SyntheticTheorem) -> bool:
        """
        Determine if a theorem is "interesting" (non-trivial).
        
        Filtering criteria:
        1. Not a tautology (e.g., x=x)
        2. Not already known
        3. Has sufficient complexity
        4. Shows novel structural patterns
        """
        # Check for deduplication
        thm_hash = theorem.compute_hash()
        if thm_hash in self.seen_hashes:
            return False
        self.seen_hashes.add(thm_hash)
        
        # Filter tautologies
        if self._is_tautology(theorem):
            return False
        
        # Check complexity threshold
        if theorem.complexity_score < 0.1:
            return False
        
        # Check novelty against known patterns
        if not self._is_novel(theorem):
            return False
        
        return True
    
    def _is_tautology(self, theorem: SyntheticTheorem) -> bool:
        """Check if theorem is a trivial tautology"""
        conclusion = theorem.conclusion
        
        # Check for x = x type tautologies
        if isinstance(conclusion, sp.Eq):
            if conclusion.lhs == conclusion.rhs:
                return True
            # Check if simplification makes them equal
            try:
                diff = sp.simplify(conclusion.lhs - conclusion.rhs)
                if diff == 0:
                    return True
            except:
                pass
        
        return False
    
    def _is_novel(self, theorem: SyntheticTheorem) -> bool:
        """Check if theorem pattern is novel"""
        # Extract structural pattern
        pattern = self._extract_pattern(theorem)
        
        # Track pattern frequency
        self.pattern_counts[pattern] = self.pattern_counts.get(pattern, 0) + 1
        
        # Novel if not seen too often (but seen enough to be reliable)
        count = self.pattern_counts[pattern]
        return 3 <= count <= 100  # Sweet spot for novelty
    
    def _extract_pattern(self, theorem: SyntheticTheorem) -> str:
        """Extract structural pattern for novelty detection"""
        # Simplified pattern extraction
        conclusion_type = type(theorem.conclusion).__name__
        premise_types = [type(p).__name__ for p in theorem.premises]
        return f"{theorem.domain}:{conclusion_type}:{','.join(premise_types)}"
    
    def _elevate_to_candidate(self, theorem: SyntheticTheorem) -> Optional[CandidateConjecture]:
        """Elevate interesting theorem to candidate conjecture"""
        # Compute interestingness score
        interestingness = self._compute_interestingness(theorem)
        
        # Compute cross-domain applicability
        applicability = self._assess_cross_domain(theorem)
        
        return CandidateConjecture(
            conjecture_id=f"cand_{theorem.theorem_id}",
            source_theorem=theorem,
            interestingness_score=interestingness,
            novelty_score=theorem.novelty_score,
            cross_domain_applicability=applicability
        )
    
    def _compute_interestingness(self, theorem: SyntheticTheorem) -> float:
        """Compute interestingness score"""
        score = theorem.complexity_score * 0.4
        score += len(theorem.derivation_steps) * 0.1
        score += (1.0 - theorem.novelty_score) * 0.3  # Rarer = more interesting
        return min(1.0, score)
    
    def _assess_cross_domain(self, theorem: SyntheticTheorem) -> List[str]:
        """Assess which domains might benefit from this theorem"""
        domains = [theorem.domain]
        
        # Check for cross-domain symbols
        expr_str = str(theorem.conclusion)
        if 'sin' in expr_str or 'cos' in expr_str:
            domains.append('trigonometry')
        if 'exp' in expr_str or 'log' in expr_str:
            domains.append('analysis')
        if 'Mod' in expr_str or 'gcd' in expr_str:
            domains.append('number_theory')
        
        return list(set(domains))


class ConjectureFormalizer:
    """
    Agent 1.3: Conjecture Formalizer
    
    Takes raw relationships from the Filter and translates them into
    rigorous Lean or Isabelle statements.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 1
    """
    
    def __init__(self, omdoc_encoder=None, lean_translator=None):
        self.omdoc_encoder = omdoc_encoder
        self.lean_translator = lean_translator
        
    def formalize(self, candidate: CandidateConjecture) -> CandidateConjecture:
        """
        Formalize a candidate conjecture into Lean4/OMDoc representations.
        """
        # Generate Lean4 statement
        candidate.lean4_statement = self._to_lean4(candidate)
        
        # Generate OMDoc representation
        candidate.omdoc_representation = self._to_omdoc(candidate)
        
        # Store SymPy form
        candidate.sympy_form = candidate.source_theorem.conclusion
        
        # Update status
        candidate.status = ConjectureStatus.FORMALIZED
        
        return candidate
    
    def _to_lean4(self, candidate: CandidateConjecture) -> str:
        """Convert conjecture to Lean4 theorem statement"""
        theorem = candidate.source_theorem
        
        # Build variable declarations
        vars_used = set()
        for expr in theorem.premises + [theorem.conclusion]:
            vars_used.update(expr.free_symbols)
        
        var_decls = " ".join([f"({str(v)} : ℝ)" for v in vars_used])
        
        # Build hypothesis
        hypotheses = []
        for i, premise in enumerate(theorem.premises):
            hyp = self._sympy_to_lean(premise)
            hypotheses.append(f"(h{i} : {hyp})")
        
        hyp_str = " ".join(hypotheses)
        
        # Build conclusion
        conclusion = self._sympy_to_lean(theorem.conclusion)
        
        # Construct theorem statement
        lean_code = f"""
theorem {candidate.conjecture_id} {var_decls} {hyp_str} : {conclusion} := by
  sorry -- To be proven by Deep Search Team
"""
        return lean_code.strip()
    
    def _sympy_to_lean(self, expr: sp.Expr) -> str:
        """Convert SymPy expression to Lean4 syntax"""
        if isinstance(expr, sp.Eq):
            lhs = self._sympy_to_lean(expr.lhs)
            rhs = self._sympy_to_lean(expr.rhs)
            return f"{lhs} = {rhs}"
        elif isinstance(expr, sp.Gt):
            return f"{expr.lhs} > {expr.rhs}"
        elif isinstance(expr, sp.Lt):
            return f"{expr.lhs} < {expr.rhs}"
        elif isinstance(expr, sp.Add):
            terms = [self._sympy_to_lean(arg) for arg in expr.args]
            return " + ".join(terms)
        elif isinstance(expr, sp.Mul):
            terms = [self._sympy_to_lean(arg) for arg in expr.args]
            return " * ".join(terms)
        elif isinstance(expr, sp.Pow):
            base = self._sympy_to_lean(expr.base)
            exp = self._sympy_to_lean(expr.exp)
            return f"({base})^({exp})"
        elif isinstance(expr, sp.Symbol):
            return str(expr)
        elif isinstance(expr, (int, float)):
            return str(expr)
        else:
            return str(expr)
    
    def _to_omdoc(self, candidate: CandidateConjecture) -> str:
        """Convert conjecture to OMDoc/OpenMath XML"""
        theorem = candidate.source_theorem
        
        omdoc = f"""
<omdoc xmlns="http://www.mathweb.org/omdoc">
  <theory name="{candidate.conjecture_id}">
    <assertion type="conjecture" id="{candidate.conjecture_id}">
      <CMP>{theorem.to_natural_language()}</CMP>
      <FMP>
        <OMOBJ>
          {self._sympy_to_openmath(theorem.conclusion)}
        </OMOBJ>
      </FMP>
    </assertion>
  </theory>
</omdoc>
"""
        return omdoc.strip()
    
    def _sympy_to_openmath(self, expr: sp.Expr) -> str:
        """Convert SymPy to OpenMath XML (simplified)"""
        if isinstance(expr, sp.Symbol):
            return f'<OMV name="{str(expr)}"/>'
        elif isinstance(expr, (int, float)):
            return f'<OMI>{expr}</OMI>'
        elif isinstance(expr, sp.Eq):
            return f"""<OMA>
  <OMS cd="relation1" name="eq"/>
  {self._sympy_to_openmath(expr.lhs)}
  {self._sympy_to_openmath(expr.rhs)}
</OMA>"""
        else:
            return f'<OMS cd="unknown" name="{type(expr).__name__}"/>'


# =============================================================================
# SECTION 2: DEEP SEARCH TEAM ("The Explorer")
# =============================================================================

@dataclass
class ProofState:
    """
    Represents a state in the proof search tree.
    """
    state_id: str
    goal: str  # Current proof goal in Lean4 syntax
    hypotheses: List[str]  # Available hypotheses
    depth: int
    parent_id: Optional[str] = None
    tactic_applied: Optional[str] = None
    value_estimate: float = 0.0
    visit_count: int = 0
    children: List[str] = field(default_factory=list)
    
    def is_terminal(self) -> bool:
        """Check if this is a terminal state (proven or dead end)"""
        return self.goal == "⊤" or self.visit_count > 100


@dataclass
class TacticCandidate:
    """A potential proof step with its probability"""
    tactic: str
    probability: float
    expected_subgoals: int
    tactical_notes: str = ""


class PolicyNetwork(nn.Module):
    """
    Agent 2.1: The Tactician
    
    Specialized implementation of AlphaProof Prover. Generates massive
    search trees of potential proof steps (tactics).
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 2
    """
    
    # Common Lean4 tactics
    TACTIC_VOCABULARY = [
        "intro", "apply", "exact", "rfl", "simp", "ring", "linarith",
        "induction", "cases", "constructor", "use", "exists", "have",
        "rw", "conv", "norm_num", "decide", "trivial", "assumption",
        "contradiction", "exfalso", "ext", "funext", "congr", "calc",
        "by_contra", "push_neg", "rcases", "obtain", "refine", "specialize"
    ]
    
    def __init__(self, hidden_dim: int = 512, num_tactics: int = None):
        super().__init__()
        
        if num_tactics is None:
            num_tactics = len(self.TACTIC_VOCABULARY)
        
        self.hidden_dim = hidden_dim
        self.num_tactics = num_tactics
        
        # Simplified transformer encoder for proof states
        self.embedding = nn.Embedding(10000, hidden_dim)  # Token vocabulary
        encoder_layer = nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=8)
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=4)
        
        # Policy head: predicts tactic probabilities
        self.policy_head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, num_tactics)
        )
        
    def forward(self, proof_state_tokens: torch.Tensor) -> torch.Tensor:
        """
        Forward pass to get tactic probabilities.
        
        Args:
            proof_state_tokens: Tokenized proof state [batch, seq_len]
            
        Returns:
            Tactic probabilities [batch, num_tactics]
        """
        embedded = self.embedding(proof_state_tokens)
        encoded = self.encoder(embedded)
        pooled = encoded.mean(dim=1)  # Simple average pooling
        logits = self.policy_head(pooled)
        return torch.softmax(logits, dim=-1)
    
    def generate_tactics(
        self, 
        proof_state: ProofState, 
        top_k: int = 5
    ) -> List[TacticCandidate]:
        """
        Generate top-k tactic candidates for a proof state.
        """
        # Tokenize proof state (simplified)
        tokens = self._tokenize_state(proof_state)
        
        with torch.no_grad():
            probs = self(tokens.unsqueeze(0))[0]
        
        # Get top-k tactics
        top_probs, top_indices = torch.topk(probs, k=min(top_k, self.num_tactics))
        
        candidates = []
        for prob, idx in zip(top_probs.tolist(), top_indices.tolist()):
            tactic = self.TACTIC_VOCABULARY[idx] if idx < len(self.TACTIC_VOCABULARY) else f"tactic_{idx}"
            candidates.append(TacticCandidate(
                tactic=tactic,
                probability=prob,
                expected_subgoals=1,  # Simplified
                tactical_notes=f"Suggested by policy network with p={prob:.3f}"
            ))
        
        return candidates
    
    def _tokenize_state(self, state: ProofState) -> torch.Tensor:
        """Simple tokenization of proof state"""
        # In production, would use proper tokenizer
        text = f"{state.goal} {' '.join(state.hypotheses)}"
        tokens = [hash(c) % 10000 for c in text][:256]
        tokens += [0] * (256 - len(tokens))  # Pad
        return torch.tensor(tokens)


class CriticNetwork(nn.Module):
    """
    Agent 2.2: The Evaluator
    
    Value-function agent that estimates the probability that a specific
    branch of the search tree will lead to a successful proof.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 2
    """
    
    def __init__(self, hidden_dim: int = 512):
        super().__init__()
        
        self.hidden_dim = hidden_dim
        
        # Same encoder architecture as Policy Network
        self.embedding = nn.Embedding(10000, hidden_dim)
        encoder_layer = nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=8)
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=4)
        
        # Value head: predicts proof success probability
        self.value_head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1),
            nn.Sigmoid()
        )
        
    def forward(self, proof_state_tokens: torch.Tensor) -> torch.Tensor:
        """
        Estimate value (proof success probability) for states.
        
        Returns:
            Value estimates [batch, 1] in range [0, 1]
        """
        embedded = self.embedding(proof_state_tokens)
        encoded = self.encoder(embedded)
        pooled = encoded.mean(dim=1)
        value = self.value_head(pooled)
        return value
    
    def evaluate(self, proof_state: ProofState) -> float:
        """Evaluate a single proof state"""
        tokens = self._tokenize_state(proof_state)
        with torch.no_grad():
            value = self(tokens.unsqueeze(0))[0, 0].item()
        return value
    
    def _tokenize_state(self, state: ProofState) -> torch.Tensor:
        """Simple tokenization of proof state"""
        text = f"{state.goal} {' '.join(state.hypotheses)}"
        tokens = [hash(c) % 10000 for c in text][:256]
        tokens += [0] * (256 - len(tokens))
        return torch.tensor(tokens)


class SearchTreeManager:
    """
    Agent 2.3: Search Tree Manager
    
    Manages the Product-Node search architecture. Tracks thousands of
    parallel proof attempts, prioritizing promising branches.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 2
    """
    
    def __init__(
        self, 
        policy_network: PolicyNetwork,
        critic_network: CriticNetwork,
        exploration_constant: float = 1.4
    ):
        self.policy = policy_network
        self.critic = critic_network
        self.c_puct = exploration_constant
        
        # Search tree storage
        self.states: Dict[str, ProofState] = {}
        self.root_id: Optional[str] = None
        
        # Search statistics
        self.total_expansions = 0
        self.max_depth_reached = 0
        
    def initialize_search(self, conjecture: CandidateConjecture) -> str:
        """Initialize search tree with root state from conjecture"""
        root_id = f"root_{conjecture.conjecture_id}"
        
        root_state = ProofState(
            state_id=root_id,
            goal=conjecture.lean4_statement or str(conjecture.source_theorem.conclusion),
            hypotheses=[str(p) for p in conjecture.source_theorem.premises],
            depth=0
        )
        
        # Get initial value estimate
        root_state.value_estimate = self.critic.evaluate(root_state)
        
        self.states[root_id] = root_state
        self.root_id = root_id
        
        return root_id
    
    def search(self, num_simulations: int = 1000) -> Optional[List[str]]:
        """
        Run MCTS-style search for proof.
        
        Returns proof steps if successful, None otherwise.
        """
        for _ in range(num_simulations):
            # Selection: traverse tree using UCB1
            leaf_id = self._select()
            
            # Expansion: add new states
            if not self.states[leaf_id].is_terminal():
                child_ids = self._expand(leaf_id)
                
                # Evaluate new states
                for child_id in child_ids:
                    self.states[child_id].value_estimate = self.critic.evaluate(
                        self.states[child_id]
                    )
            
            # Backpropagation: update values up the tree
            self._backpropagate(leaf_id)
            
            # Check for success
            if self._is_proven():
                return self._extract_proof()
        
        return None
    
    def _select(self) -> str:
        """Select leaf node using UCB1"""
        current_id = self.root_id
        
        while True:
            state = self.states[current_id]
            
            if not state.children or state.is_terminal():
                return current_id
            
            # UCB1 selection
            best_child = None
            best_score = -float('inf')
            
            for child_id in state.children:
                child = self.states[child_id]
                
                # UCB1 formula
                exploitation = child.value_estimate
                exploration = self.c_puct * np.sqrt(
                    np.log(state.visit_count + 1) / (child.visit_count + 1)
                )
                score = exploitation + exploration
                
                if score > best_score:
                    best_score = score
                    best_child = child_id
            
            current_id = best_child
        
        return current_id
    
    def _expand(self, state_id: str) -> List[str]:
        """Expand state with new children"""
        state = self.states[state_id]
        
        # Generate candidate tactics
        tactics = self.policy.generate_tactics(state, top_k=5)
        
        child_ids = []
        for tactic in tactics:
            child_id = f"{state_id}_{tactic.tactic}"
            
            # Create child state (simplified - would use Lean prover in production)
            child_state = ProofState(
                state_id=child_id,
                goal=f"subgoal after {tactic.tactic}",  # Simplified
                hypotheses=state.hypotheses.copy(),
                depth=state.depth + 1,
                parent_id=state_id,
                tactic_applied=tactic.tactic
            )
            
            self.states[child_id] = child_state
            child_ids.append(child_id)
            state.children.append(child_id)
        
        self.total_expansions += len(child_ids)
        self.max_depth_reached = max(self.max_depth_reached, state.depth + 1)
        
        return child_ids
    
    def _backpropagate(self, leaf_id: str):
        """Backpropagate value estimates up the tree"""
        current_id = leaf_id
        
        while current_id is not None:
            state = self.states[current_id]
            state.visit_count += 1
            
            # Update value based on children
            if state.children:
                child_values = [self.states[c].value_estimate for c in state.children]
                state.value_estimate = max(child_values)
            
            current_id = state.parent_id
    
    def _is_proven(self) -> bool:
        """Check if proof is complete"""
        for state in self.states.values():
            if state.goal == "⊤" or state.goal.lower() == "done":
                return True
        return False
    
    def _extract_proof(self) -> List[str]:
        """Extract proof steps from successful path"""
        # Find terminal success state
        success_id = None
        for state_id, state in self.states.items():
            if state.goal == "⊤" or state.goal.lower() == "done":
                success_id = state_id
                break
        
        if success_id is None:
            return []
        
        # Trace back to root
        proof_steps = []
        current_id = success_id
        
        while current_id is not None:
            state = self.states[current_id]
            if state.tactic_applied:
                proof_steps.append(state.tactic_applied)
            current_id = state.parent_id
        
        proof_steps.reverse()
        return proof_steps


# =============================================================================
# SECTION 3: ALGORITHM DISCOVERY UNIT ("FunSearch Pattern")
# =============================================================================

@dataclass
class CodeCandidate:
    """A candidate code solution in the evolutionary search"""
    candidate_id: str
    code: str
    generation: int
    parent_id: Optional[str] = None
    fitness_score: float = 0.0
    execution_time_ms: float = 0.0
    correctness_score: float = 0.0
    mutation_type: str = 'initial'


@dataclass
class ProblemSpecification:
    """Specification for algorithm discovery problem"""
    problem_id: str
    description: str
    function_signature: str  # e.g., "def solve(items: List[int], capacity: int) -> int"
    test_cases: List[Tuple[Any, Any]]  # (input, expected_output)
    fitness_fn: Optional[Callable] = None  # Custom fitness function
    timeout_seconds: float = 5.0


class CodeEvolutionaryProposer:
    """
    Agent 3.1: Code Evolutionary Proposer
    
    LLM-based agent that generates Python/Julia code snippets
    representing heuristics. Uses evolutionary logic.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 3
    """
    
    MUTATION_TYPES = [
        'tweak_constant',
        'swap_operators',
        'add_condition',
        'remove_code',
        'restructure_loop',
        'combine_parents'
    ]
    
    def __init__(self, llm_client=None, problem_spec: ProblemSpecification = None):
        self.llm = llm_client
        self.problem_spec = problem_spec
        self.population: List[CodeCandidate] = []
        self.elite_size = 10
        self.generation = 0
        
    def initialize_population(self, size: int = 20) -> List[CodeCandidate]:
        """Generate initial population of code candidates"""
        candidates = []
        
        for i in range(size):
            code = self._generate_initial_code()
            candidate = CodeCandidate(
                candidate_id=f"gen0_{i}",
                code=code,
                generation=0,
                mutation_type='initial'
            )
            candidates.append(candidate)
        
        self.population = candidates
        return candidates
    
    def _generate_initial_code(self) -> str:
        """Generate initial code based on problem specification"""
        if self.problem_spec is None:
            return self._generate_generic_heuristic()
        
        # Template-based generation
        templates = [
            self._greedy_template(),
            self._dynamic_programming_template(),
            self._recursive_template(),
            self._iterative_template()
        ]
        
        return random.choice(templates)
    
    def _generate_generic_heuristic(self) -> str:
        """Generate a generic optimization heuristic"""
        return '''
def solve(data):
    """Generic heuristic solution"""
    result = []
    sorted_data = sorted(data, key=lambda x: x[1], reverse=True)
    
    for item in sorted_data:
        if can_add(result, item):
            result.append(item)
    
    return optimize(result)
'''
    
    def _greedy_template(self) -> str:
        """Greedy algorithm template"""
        return f'''
{self.problem_spec.function_signature}:
    """Greedy approach"""
    solution = []
    remaining = list(items)
    
    while remaining:
        best = max(remaining, key=lambda x: score(x, solution))
        if feasible(solution + [best]):
            solution.append(best)
        remaining.remove(best)
    
    return evaluate(solution)
'''
    
    def _dynamic_programming_template(self) -> str:
        """DP template"""
        return f'''
{self.problem_spec.function_signature}:
    """Dynamic programming approach"""
    n = len(items)
    dp = [[0] * (capacity + 1) for _ in range(n + 1)]
    
    for i in range(1, n + 1):
        for w in range(capacity + 1):
            if items[i-1] <= w:
                dp[i][w] = max(dp[i-1][w], dp[i-1][w-items[i-1]] + values[i-1])
            else:
                dp[i][w] = dp[i-1][w]
    
    return dp[n][capacity]
'''
    
    def _recursive_template(self) -> str:
        """Recursive template with memoization"""
        return f'''
{self.problem_spec.function_signature}:
    """Recursive approach with memoization"""
    from functools import lru_cache
    
    @lru_cache(maxsize=None)
    def helper(i, remaining):
        if i >= len(items) or remaining <= 0:
            return 0
        
        skip = helper(i + 1, remaining)
        take = 0
        if items[i] <= remaining:
            take = values[i] + helper(i + 1, remaining - items[i])
        
        return max(skip, take)
    
    return helper(0, capacity)
'''
    
    def _iterative_template(self) -> str:
        """Iterative template"""
        return f'''
{self.problem_spec.function_signature}:
    """Iterative approach"""
    best = 0
    current = []
    
    for i, item in enumerate(items):
        if sum(current) + item <= capacity:
            current.append(item)
            best = max(best, sum(current))
    
    return best
'''
    
    def evolve(self, evaluated_population: List[CodeCandidate]) -> List[CodeCandidate]:
        """Evolve population based on fitness"""
        self.generation += 1
        
        # Sort by fitness
        sorted_pop = sorted(evaluated_population, key=lambda c: c.fitness_score, reverse=True)
        
        # Keep elite
        elite = sorted_pop[:self.elite_size]
        
        # Generate new candidates through mutation and crossover
        new_population = list(elite)
        
        while len(new_population) < len(evaluated_population):
            parent = random.choice(elite)
            mutation_type = random.choice(self.MUTATION_TYPES)
            
            child_code = self._mutate(parent.code, mutation_type)
            child = CodeCandidate(
                candidate_id=f"gen{self.generation}_{len(new_population)}",
                code=child_code,
                generation=self.generation,
                parent_id=parent.candidate_id,
                mutation_type=mutation_type
            )
            new_population.append(child)
        
        self.population = new_population
        return new_population
    
    def _mutate(self, code: str, mutation_type: str) -> str:
        """Apply mutation to code"""
        if mutation_type == 'tweak_constant':
            return self._tweak_constants(code)
        elif mutation_type == 'swap_operators':
            return self._swap_operators(code)
        elif mutation_type == 'add_condition':
            return self._add_condition(code)
        elif mutation_type == 'remove_code':
            return self._remove_code(code)
        else:
            return code  # No mutation
    
    def _tweak_constants(self, code: str) -> str:
        """Tweak numeric constants in code"""
        import re
        
        def tweak(match):
            val = float(match.group())
            new_val = val * random.uniform(0.5, 2.0)
            return str(int(new_val) if val == int(val) else round(new_val, 2))
        
        return re.sub(r'\b\d+\.?\d*\b', tweak, code)
    
    def _swap_operators(self, code: str) -> str:
        """Swap operators in code"""
        swaps = [
            ('+', '-'), ('-', '+'),
            ('*', '/'), ('/', '*'),
            ('>', '<'), ('<', '>'),
            ('>=', '<='), ('<=', '>='),
            ('max', 'min'), ('min', 'max')
        ]
        
        for old, new in random.sample(swaps, 2):
            if old in code:
                code = code.replace(old, new, 1)
                break
        
        return code
    
    def _add_condition(self, code: str) -> str:
        """Add a conditional check"""
        conditions = [
            "if len(items) > 0:",
            "if remaining > 0:",
            "if i < len(items):",
        ]
        # Would insert condition in appropriate location
        return code
    
    def _remove_code(self, code: str) -> str:
        """Remove a line of code (carefully)"""
        lines = code.split('\n')
        if len(lines) > 5:
            # Remove a random non-essential line
            idx = random.randint(2, len(lines) - 2)
            lines.pop(idx)
        return '\n'.join(lines)


class SandboxEvaluator:
    """
    Agent 3.2: Sandbox Evaluator
    
    Secure execution environment that runs proposed code against
    rigorous test sets.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 3
    """
    
    def __init__(
        self, 
        problem_spec: ProblemSpecification,
        timeout_seconds: float = 5.0
    ):
        self.problem_spec = problem_spec
        self.timeout = timeout_seconds
        
    def evaluate(self, candidate: CodeCandidate) -> CodeCandidate:
        """
        Evaluate a code candidate in sandbox.
        
        Returns updated candidate with fitness scores.
        """
        start_time = time.time()
        
        try:
            # Write code to temp file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
                f.write(candidate.code)
                f.write(self._generate_test_harness())
                temp_path = f.name
            
            # Execute in subprocess (sandbox)
            result = subprocess.run(
                ['python', temp_path],
                capture_output=True,
                text=True,
                timeout=self.timeout
            )
            
            execution_time = (time.time() - start_time) * 1000
            candidate.execution_time_ms = execution_time
            
            # Parse results
            if result.returncode == 0:
                scores = self._parse_scores(result.stdout)
                candidate.correctness_score = scores.get('correctness', 0.0)
                candidate.fitness_score = self._compute_fitness(
                    scores, execution_time
                )
            else:
                candidate.fitness_score = 0.0
                candidate.correctness_score = 0.0
                
        except subprocess.TimeoutExpired:
            candidate.fitness_score = 0.0
            candidate.execution_time_ms = self.timeout * 1000
            
        except Exception as e:
            candidate.fitness_score = 0.0
            
        return candidate
    
    def _generate_test_harness(self) -> str:
        """Generate test harness code"""
        test_code = "\n\n# Test harness\n"
        test_code += "import json\n"
        test_code += "results = {'passed': 0, 'failed': 0, 'total': 0}\n"
        
        for i, (input_val, expected) in enumerate(self.problem_spec.test_cases):
            test_code += f"""
try:
    result = solve({repr(input_val)})
    if result == {repr(expected)}:
        results['passed'] += 1
    else:
        results['failed'] += 1
except:
    results['failed'] += 1
results['total'] += 1
"""
        
        test_code += "print(json.dumps(results))\n"
        return test_code
    
    def _parse_scores(self, stdout: str) -> Dict[str, float]:
        """Parse test results from stdout"""
        try:
            results = json.loads(stdout.strip().split('\n')[-1])
            correctness = results['passed'] / max(results['total'], 1)
            return {'correctness': correctness}
        except:
            return {'correctness': 0.0}
    
    def _compute_fitness(self, scores: Dict[str, float], execution_time: float) -> float:
        """Compute overall fitness score"""
        correctness = scores.get('correctness', 0.0)
        
        # Speed bonus (faster = better, up to 20% bonus)
        speed_bonus = max(0, 1.0 - execution_time / 1000) * 0.2
        
        # Final fitness
        fitness = correctness * 0.8 + speed_bonus
        
        return fitness


class HeuristicDistiller:
    """
    Agent 3.3: Heuristic Distiller
    
    Analyzes successful code to extract the underlying mathematical
    principle into human-readable form.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 3
    """
    
    def __init__(self, llm_client=None):
        self.llm = llm_client
        
    def distill(self, successful_candidate: CodeCandidate) -> Dict[str, Any]:
        """
        Extract mathematical principle from successful code.
        
        Returns:
            Dictionary with prose explanation, formal spec, and applicable domains
        """
        # Analyze code structure
        analysis = self._analyze_code_structure(successful_candidate.code)
        
        # Extract key patterns
        patterns = self._extract_patterns(successful_candidate.code)
        
        # Generate prose explanation
        explanation = self._generate_explanation(analysis, patterns)
        
        # Identify applicable problem classes
        domains = self._identify_domains(analysis)
        
        return {
            'candidate_id': successful_candidate.candidate_id,
            'prose_explanation': explanation,
            'key_patterns': patterns,
            'algorithmic_class': analysis.get('class', 'unknown'),
            'applicable_domains': domains,
            'code': successful_candidate.code,
            'fitness_score': successful_candidate.fitness_score
        }
    
    def _analyze_code_structure(self, code: str) -> Dict[str, Any]:
        """Analyze code structure to identify algorithm type"""
        analysis = {
            'has_recursion': 'def ' in code and code.count('def ') > 1,
            'has_memoization': 'lru_cache' in code or 'memo' in code.lower(),
            'has_loops': 'for ' in code or 'while ' in code,
            'uses_sorting': 'sorted' in code or '.sort()' in code,
            'uses_max_min': 'max(' in code or 'min(' in code,
            'has_dp_table': '[[' in code and 'for ' in code,
        }
        
        # Classify algorithm
        if analysis['has_dp_table']:
            analysis['class'] = 'dynamic_programming'
        elif analysis['has_recursion'] and analysis['has_memoization']:
            analysis['class'] = 'memoized_recursion'
        elif analysis['uses_sorting'] and not analysis['has_dp_table']:
            analysis['class'] = 'greedy'
        elif analysis['has_loops'] and analysis['uses_max_min']:
            analysis['class'] = 'local_search'
        else:
            analysis['class'] = 'heuristic'
        
        return analysis
    
    def _extract_patterns(self, code: str) -> List[str]:
        """Extract key algorithmic patterns"""
        patterns = []
        
        if 'sorted(' in code:
            patterns.append("Sorting as preprocessing step")
        if 'max(' in code:
            patterns.append("Greedy maximum selection")
        if 'for i in range' in code:
            patterns.append("Linear iteration pattern")
        if 'while ' in code:
            patterns.append("Condition-based iteration")
        if 'dp[' in code or 'memo[' in code:
            patterns.append("Subproblem caching")
        if '+ 1' in code or '- 1' in code:
            patterns.append("Incremental update")
        
        return patterns
    
    def _generate_explanation(
        self, 
        analysis: Dict[str, Any], 
        patterns: List[str]
    ) -> str:
        """Generate prose explanation of the heuristic"""
        algo_class = analysis.get('class', 'unknown')
        
        explanation = f"This algorithm uses a {algo_class.replace('_', ' ')} approach. "
        
        if patterns:
            explanation += f"Key techniques include: {', '.join(patterns)}. "
        
        if algo_class == 'dynamic_programming':
            explanation += "It breaks the problem into overlapping subproblems and builds up solutions from smaller instances."
        elif algo_class == 'greedy':
            explanation += "It makes locally optimal choices at each step, hoping to find a global optimum."
        elif algo_class == 'memoized_recursion':
            explanation += "It combines recursive problem decomposition with result caching to avoid redundant computation."
        
        return explanation
    
    def _identify_domains(self, analysis: Dict[str, Any]) -> List[str]:
        """Identify problem domains where this heuristic applies"""
        domains = []
        
        algo_class = analysis.get('class', 'unknown')
        
        if algo_class in ['dynamic_programming', 'memoized_recursion']:
            domains.extend(['optimization', 'counting', 'shortest_path'])
        if algo_class == 'greedy':
            domains.extend(['scheduling', 'knapsack', 'selection'])
        if analysis.get('uses_sorting'):
            domains.append('sorting_based')
        
        return list(set(domains))


# =============================================================================
# SECTION 4: UNDECIDABILITY NAVIGATOR ("Boundary Watcher")
# =============================================================================

class DecidabilityClass(Enum):
    """Classification of decidability for a problem"""
    DECIDABLE = 'decidable'
    SEMI_DECIDABLE = 'semi_decidable'
    UNDECIDABLE = 'undecidable'
    UNKNOWN = 'unknown'


@dataclass
class DecidabilityAssessment:
    """Assessment result from Decidability Checker"""
    problem_id: str
    decidability_class: DecidabilityClass
    theory_classification: str
    confidence: float
    reasoning: str
    recommended_mode: str  # 'solver' or 'heuristic_search'
    resource_bounds: Optional[Dict[str, int]] = None


class DecidabilityChecker:
    """
    Agent 4.1: Decidability Checker
    
    Meta-analyst that inspects the logical structure of a problem
    before the Deep Search Team commits resources.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 4
    """
    
    # Known decidable theories
    DECIDABLE_THEORIES = {
        'presburger_arithmetic',
        'real_closed_fields',
        'propositional_logic',
        'monadic_second_order_logic_trees',
        'algebraic_geometry_quantifier_free',
        'linear_arithmetic',
        'boolean_satisfiability'
    }
    
    # Known undecidable theories
    UNDECIDABLE_THEORIES = {
        'peano_arithmetic',
        'diophantine_equations',
        'first_order_logic',
        'word_problem_groups',
        'halting_problem',
        'post_correspondence',
        'validity_first_order_logic',
        'wang_tiles'
    }
    
    # Semi-decidable (recognizable but not co-recognizable)
    SEMI_DECIDABLE_THEORIES = {
        'theorem_proving_first_order',
        'satisfiability_first_order',
        'type_inhabitation'
    }
    
    def __init__(self):
        self.assessment_cache: Dict[str, DecidabilityAssessment] = {}
        
    def assess(self, problem: CandidateConjecture) -> DecidabilityAssessment:
        """
        Assess decidability of a problem before committing search resources.
        """
        # Check cache
        if problem.conjecture_id in self.assessment_cache:
            return self.assessment_cache[problem.conjecture_id]
        
        # Analyze problem structure
        theory = self._classify_theory(problem)
        decidability = self._determine_decidability(theory, problem)
        
        assessment = DecidabilityAssessment(
            problem_id=problem.conjecture_id,
            decidability_class=decidability,
            theory_classification=theory,
            confidence=self._compute_confidence(theory),
            reasoning=self._generate_reasoning(theory, decidability),
            recommended_mode=self._recommend_mode(decidability),
            resource_bounds=self._compute_bounds(decidability, problem)
        )
        
        self.assessment_cache[problem.conjecture_id] = assessment
        return assessment
    
    def _classify_theory(self, problem: CandidateConjecture) -> str:
        """Classify the logical theory of the problem"""
        theorem = problem.source_theorem
        expr_str = str(theorem.conclusion)
        
        # Check for number-theoretic patterns
        if 'Mod' in expr_str or 'gcd' in expr_str or 'prime' in expr_str.lower():
            if 'forall' in expr_str.lower() or 'exists' in expr_str.lower():
                return 'peano_arithmetic'
            return 'presburger_arithmetic'
        
        # Check for polynomial equations
        if '**' in expr_str and '==' in expr_str:
            if self._has_integer_constraints(theorem):
                return 'diophantine_equations'
            return 'real_closed_fields'
        
        # Check for pure logic
        if 'And' in expr_str or 'Or' in expr_str or 'Not' in expr_str:
            if 'forall' in expr_str.lower() or 'exists' in expr_str.lower():
                return 'first_order_logic'
            return 'propositional_logic'
        
        # Default
        return 'algebraic_geometry_quantifier_free'
    
    def _has_integer_constraints(self, theorem: SyntheticTheorem) -> bool:
        """Check if theorem involves integer constraints"""
        for premise in theorem.premises:
            if 'Integer' in str(premise) or 'Mod' in str(premise):
                return True
        return False
    
    def _determine_decidability(
        self, 
        theory: str, 
        problem: CandidateConjecture
    ) -> DecidabilityClass:
        """Determine decidability class"""
        if theory in self.DECIDABLE_THEORIES:
            return DecidabilityClass.DECIDABLE
        elif theory in self.UNDECIDABLE_THEORIES:
            return DecidabilityClass.UNDECIDABLE
        elif theory in self.SEMI_DECIDABLE_THEORIES:
            return DecidabilityClass.SEMI_DECIDABLE
        else:
            return DecidabilityClass.UNKNOWN
    
    def _compute_confidence(self, theory: str) -> float:
        """Compute confidence in classification"""
        if theory in self.DECIDABLE_THEORIES or theory in self.UNDECIDABLE_THEORIES:
            return 0.95
        elif theory in self.SEMI_DECIDABLE_THEORIES:
            return 0.85
        else:
            return 0.5
    
    def _generate_reasoning(
        self, 
        theory: str, 
        decidability: DecidabilityClass
    ) -> str:
        """Generate explanation for decidability assessment"""
        if decidability == DecidabilityClass.DECIDABLE:
            return f"Problem is in {theory}, which is known to be decidable. Full search is safe."
        elif decidability == DecidabilityClass.UNDECIDABLE:
            return f"Problem involves {theory}, which is undecidable (Gödel/Turing). Switch to heuristic search with bounds."
        elif decidability == DecidabilityClass.SEMI_DECIDABLE:
            return f"Problem is semi-decidable ({theory}). Search may find proof but cannot prove impossibility."
        else:
            return f"Unable to classify {theory}. Proceed with caution and resource limits."
    
    def _recommend_mode(self, decidability: DecidabilityClass) -> str:
        """Recommend search mode based on decidability"""
        if decidability == DecidabilityClass.DECIDABLE:
            return 'solver'
        else:
            return 'heuristic_search'
    
    def _compute_bounds(
        self, 
        decidability: DecidabilityClass, 
        problem: CandidateConjecture
    ) -> Optional[Dict[str, int]]:
        """Compute resource bounds for search"""
        if decidability == DecidabilityClass.DECIDABLE:
            return None  # No bounds needed
        
        # Set bounds for non-decidable problems
        complexity = problem.source_theorem.complexity_score
        
        return {
            'max_depth': int(20 * (1 + complexity)),
            'max_expansions': int(10000 * (1 + complexity)),
            'timeout_seconds': int(300 * (1 + complexity)),
            'max_memory_mb': 4096
        }


@dataclass
class ProofStateSummary:
    """Summary generated for Human-in-the-Loop guidance"""
    problem_id: str
    current_goal: str
    proven_subgoals: List[str]
    remaining_subgoals: List[str]
    attempted_tactics: List[str]
    failure_reasons: List[str]
    suggested_directions: List[str]
    human_query: str


class InteractiveGuidanceLiaison:
    """
    Agent 4.2: Interactive Guidance Liaison
    
    Human-in-the-Loop interface agent. When Deep Search hits a
    theoretical wall, generates a Proof State Summary and requests
    specific guidance from a human mathematician.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 4
    """
    
    def __init__(self, notification_callback: Callable = None):
        self.notification_callback = notification_callback
        self.pending_requests: Dict[str, ProofStateSummary] = {}
        self.received_guidance: Dict[str, str] = {}
        
    def request_guidance(
        self, 
        problem: CandidateConjecture,
        search_state: Dict[str, Any]
    ) -> ProofStateSummary:
        """
        Generate Proof State Summary and request human guidance.
        """
        # Analyze search state
        attempted_tactics = search_state.get('attempted_tactics', [])
        failure_reasons = self._analyze_failures(search_state)
        suggestions = self._generate_suggestions(search_state)
        
        # Build human query
        human_query = self._formulate_query(problem, search_state, suggestions)
        
        summary = ProofStateSummary(
            problem_id=problem.conjecture_id,
            current_goal=str(problem.source_theorem.conclusion),
            proven_subgoals=search_state.get('proven', []),
            remaining_subgoals=search_state.get('remaining', []),
            attempted_tactics=attempted_tactics,
            failure_reasons=failure_reasons,
            suggested_directions=suggestions,
            human_query=human_query
        )
        
        self.pending_requests[problem.conjecture_id] = summary
        
        # Notify if callback registered
        if self.notification_callback:
            self.notification_callback(summary)
        
        return summary
    
    def _analyze_failures(self, search_state: Dict[str, Any]) -> List[str]:
        """Analyze why search failed"""
        reasons = []
        
        if search_state.get('timeout'):
            reasons.append("Search timed out before finding proof")
        if search_state.get('max_depth_reached'):
            reasons.append("Maximum search depth reached")
        if search_state.get('stuck_subgoals'):
            reasons.append(f"Stuck on subgoals: {search_state['stuck_subgoals']}")
        if not search_state.get('attempted_tactics'):
            reasons.append("No applicable tactics found")
        
        return reasons
    
    def _generate_suggestions(self, search_state: Dict[str, Any]) -> List[str]:
        """Generate suggested directions for human"""
        suggestions = []
        
        # Based on what was tried, suggest alternatives
        tried = set(search_state.get('attempted_tactics', []))
        
        if 'induction' not in tried:
            suggestions.append("Consider induction on a suitable variable")
        if 'contradiction' not in tried:
            suggestions.append("Try proof by contradiction")
        if 'cases' not in tried:
            suggestions.append("Case analysis might help")
        if 'simp' in tried and 'ring' not in tried:
            suggestions.append("Try algebraic normalization (ring tactic)")
        
        return suggestions
    
    def _formulate_query(
        self, 
        problem: CandidateConjecture,
        search_state: Dict[str, Any],
        suggestions: List[str]
    ) -> str:
        """Formulate specific question for human"""
        query = f"I am attempting to prove: {problem.source_theorem.to_natural_language()}\n\n"
        query += f"I have tried: {', '.join(search_state.get('attempted_tactics', ['nothing']))}\n\n"
        
        if search_state.get('stuck_subgoals'):
            query += f"I am stuck on: {search_state['stuck_subgoals'][0]}\n\n"
        
        query += "Should I:\n"
        for i, suggestion in enumerate(suggestions[:3], 1):
            query += f"{i}. {suggestion}\n"
        
        query += "\nOr do you have another suggestion?"
        
        return query
    
    def receive_guidance(self, problem_id: str, guidance: str):
        """Receive guidance from human mathematician"""
        self.received_guidance[problem_id] = guidance
        if problem_id in self.pending_requests:
            del self.pending_requests[problem_id]
    
    def get_guidance(self, problem_id: str) -> Optional[str]:
        """Get received guidance for a problem"""
        return self.received_guidance.get(problem_id)


# =============================================================================
# SECTION 5: FORMAL KNOWLEDGE INTEGRATION ("The Archivist")
# =============================================================================

@dataclass
class FormalizedDiscovery:
    """A discovery that has been formalized for integration"""
    discovery_id: str
    discovery_type: str  # 'theorem', 'algorithm', 'lemma', 'heuristic'
    natural_language_statement: str
    omdoc_representation: str
    lean4_code: Optional[str] = None
    sympy_implementation: Optional[str] = None
    proof_trace_id: Optional[str] = None
    verified: bool = False
    verification_method: str = ""
    applicable_domains: List[str] = field(default_factory=list)
    embedding_vector: Optional[List[float]] = None
    created_at: datetime = field(default_factory=datetime.now)


class AutoFormalizationPipeline:
    """
    Agent 5.1: Auto-Formalization Pipeline
    
    Converts natural language or code outputs from discovery teams
    into strict OMDoc/OpenMath entries.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 5
    """
    
    def __init__(self, verification_core=None, omdoc_encoder=None):
        self.verifier = verification_core  # Phase 1 Verification Core
        self.omdoc_encoder = omdoc_encoder
        self.formalized_count = 0
        
    def formalize_theorem(
        self, 
        conjecture: CandidateConjecture,
        proof_steps: List[str]
    ) -> FormalizedDiscovery:
        """
        Formalize a proven conjecture into the knowledge base.
        """
        self.formalized_count += 1
        
        # Generate natural language statement
        nl_statement = self._generate_nl_statement(conjecture)
        
        # Generate OMDoc representation
        omdoc = self._generate_omdoc(conjecture, proof_steps)
        
        # Generate Lean4 code with proof
        lean_code = self._generate_lean_proof(conjecture, proof_steps)
        
        # Generate SymPy implementation if applicable
        sympy_impl = self._generate_sympy_implementation(conjecture)
        
        discovery = FormalizedDiscovery(
            discovery_id=f"disc_{self.formalized_count}_{conjecture.conjecture_id}",
            discovery_type='theorem',
            natural_language_statement=nl_statement,
            omdoc_representation=omdoc,
            lean4_code=lean_code,
            sympy_implementation=sympy_impl,
            proof_trace_id=conjecture.conjecture_id,
            verified=True,
            verification_method='deep_search_proof',
            applicable_domains=conjecture.cross_domain_applicability
        )
        
        return discovery
    
    def formalize_algorithm(
        self, 
        heuristic: Dict[str, Any]
    ) -> FormalizedDiscovery:
        """
        Formalize a discovered algorithm into the knowledge base.
        """
        self.formalized_count += 1
        
        discovery = FormalizedDiscovery(
            discovery_id=f"disc_{self.formalized_count}_alg_{heuristic['candidate_id']}",
            discovery_type='algorithm',
            natural_language_statement=heuristic['prose_explanation'],
            omdoc_representation=self._algorithm_to_omdoc(heuristic),
            lean4_code=None,  # Algorithms don't have Lean proofs
            sympy_implementation=heuristic['code'],
            verified=True,
            verification_method='sandbox_evaluation',
            applicable_domains=heuristic['applicable_domains']
        )
        
        return discovery
    
    def _generate_nl_statement(self, conjecture: CandidateConjecture) -> str:
        """Generate natural language theorem statement"""
        theorem = conjecture.source_theorem
        
        statement = f"Theorem ({conjecture.conjecture_id}): "
        
        if theorem.premises:
            premises = " and ".join([str(p) for p in theorem.premises])
            statement += f"If {premises}, then "
        
        statement += f"{theorem.conclusion}."
        
        return statement
    
    def _generate_omdoc(
        self, 
        conjecture: CandidateConjecture,
        proof_steps: List[str]
    ) -> str:
        """Generate OMDoc representation"""
        theorem = conjecture.source_theorem
        
        omdoc = f"""<?xml version="1.0" encoding="UTF-8"?>
<omdoc xmlns="http://www.mathweb.org/omdoc" version="1.6">
  <theory name="{conjecture.conjecture_id}">
    <assertion type="theorem" id="{conjecture.conjecture_id}">
      <CMP>{theorem.to_natural_language()}</CMP>
      <FMP>
        <OMOBJ xmlns="http://www.openmath.org/OpenMath">
          {self._expr_to_openmath(theorem.conclusion)}
        </OMOBJ>
      </FMP>
    </assertion>
    <proof id="{conjecture.conjecture_id}_proof" for="{conjecture.conjecture_id}">
      <derive>
        <CMP>Proof by: {', '.join(proof_steps)}</CMP>
      </derive>
    </proof>
  </theory>
</omdoc>"""
        return omdoc
    
    def _expr_to_openmath(self, expr: sp.Expr) -> str:
        """Convert SymPy expression to OpenMath"""
        if isinstance(expr, sp.Symbol):
            return f'<OMV name="{expr.name}"/>'
        elif isinstance(expr, sp.Integer):
            return f'<OMI>{expr}</OMI>'
        elif isinstance(expr, sp.Eq):
            return f"""<OMA>
          <OMS cd="relation1" name="eq"/>
          {self._expr_to_openmath(expr.lhs)}
          {self._expr_to_openmath(expr.rhs)}
        </OMA>"""
        else:
            return f'<OMS cd="arith1" name="{type(expr).__name__.lower()}"/>'
    
    def _generate_lean_proof(
        self, 
        conjecture: CandidateConjecture,
        proof_steps: List[str]
    ) -> str:
        """Generate Lean4 proof code"""
        # Start with the theorem statement
        lean_code = conjecture.lean4_statement or ""
        
        # Replace 'sorry' with actual proof
        if 'sorry' in lean_code:
            tactics = '\n  '.join(proof_steps) if proof_steps else 'sorry'
            lean_code = lean_code.replace('sorry', tactics)
        
        return lean_code
    
    def _generate_sympy_implementation(
        self, 
        conjecture: CandidateConjecture
    ) -> Optional[str]:
        """Generate SymPy implementation if applicable"""
        theorem = conjecture.source_theorem
        
        if theorem.domain in ['algebra', 'analysis']:
            # Generate a function that checks/applies the theorem
            impl = f"""
def {conjecture.conjecture_id.replace('-', '_')}(expr):
    '''
    Apply theorem: {theorem.to_natural_language()}
    '''
    import sympy as sp
    
    # Pattern matching implementation
    conclusion = {repr(theorem.conclusion)}
    
    # Try to match and apply
    return sp.simplify(expr - conclusion.rhs) == 0
"""
            return impl
        
        return None
    
    def _algorithm_to_omdoc(self, heuristic: Dict[str, Any]) -> str:
        """Convert algorithm to OMDoc"""
        return f"""<?xml version="1.0" encoding="UTF-8"?>
<omdoc xmlns="http://www.mathweb.org/omdoc" version="1.6">
  <theory name="algorithm_{heuristic['candidate_id']}">
    <definition id="{heuristic['candidate_id']}">
      <CMP>{heuristic['prose_explanation']}</CMP>
      <FMP>
        <OMOBJ xmlns="http://www.openmath.org/OpenMath">
          <OMS cd="algorithms" name="{heuristic['algorithmic_class']}"/>
        </OMOBJ>
      </FMP>
    </definition>
  </theory>
</omdoc>"""


class VectorDatabaseUpdater:
    """
    Agent 5.2: Vector Database Updater
    
    Updates the RAG memory infrastructure with new discoveries,
    effectively "teaching" the Phase 2 workforce.
    
    📚 Reference: Phase 6 must engineer the capacity for novel mathematical 
    discovery.docx, Section 5
    """
    
    def __init__(self, vector_db_client=None, embedding_model=None):
        self.db = vector_db_client
        self.embedding_model = embedding_model
        self.updates_count = 0
        
        # Local cache for demo
        self._local_cache: Dict[str, FormalizedDiscovery] = {}
        
    def update(self, discovery: FormalizedDiscovery) -> str:
        """
        Index a new discovery in the vector database.
        
        Returns the document ID.
        """
        self.updates_count += 1
        
        # Generate embedding
        embedding = self._generate_embedding(discovery)
        discovery.embedding_vector = embedding
        
        # Prepare document for indexing
        doc = {
            'id': discovery.discovery_id,
            'type': discovery.discovery_type,
            'content': discovery.natural_language_statement,
            'omdoc': discovery.omdoc_representation,
            'lean_code': discovery.lean4_code,
            'sympy_impl': discovery.sympy_implementation,
            'domains': discovery.applicable_domains,
            'verified': discovery.verified,
            'embedding': embedding,
            'created_at': discovery.created_at.isoformat()
        }
        
        # Index in vector database
        if self.db:
            self.db.insert(doc)
        else:
            # Local cache for demo
            self._local_cache[discovery.discovery_id] = discovery
        
        # Notify downstream systems
        self._notify_phase2_supervisors(discovery)
        
        return discovery.discovery_id
    
    def _generate_embedding(self, discovery: FormalizedDiscovery) -> List[float]:
        """Generate embedding vector for discovery"""
        if self.embedding_model:
            text = f"{discovery.natural_language_statement} {' '.join(discovery.applicable_domains)}"
            return self.embedding_model.encode(text).tolist()
        
        # Simple mock embedding for demo
        text = discovery.natural_language_statement
        embedding = [float(hash(text[i:i+5]) % 1000) / 1000 for i in range(0, min(len(text), 384), 5)]
        embedding += [0.0] * (384 - len(embedding))
        return embedding[:384]
    
    def _notify_phase2_supervisors(self, discovery: FormalizedDiscovery):
        """Notify Phase 2 supervisors of new capability"""
        # In production, would send FIPA-ACL messages to relevant supervisors
        for domain in discovery.applicable_domains:
            print(f"[VectorDBUpdater] Notifying {domain} supervisor of new {discovery.discovery_type}")
    
    def search(self, query: str, top_k: int = 5) -> List[FormalizedDiscovery]:
        """Search for relevant discoveries"""
        query_embedding = self._generate_embedding(
            FormalizedDiscovery(
                discovery_id="query",
                discovery_type="query",
                natural_language_statement=query,
                omdoc_representation=""
            )
        )
        
        if self.db:
            results = self.db.search(query_embedding, top_k=top_k)
            return results
        
        # Simple local search for demo
        return list(self._local_cache.values())[:top_k]
    
    def get_stats(self) -> Dict[str, Any]:
        """Get database statistics"""
        return {
            'total_discoveries': len(self._local_cache) if not self.db else self.db.count(),
            'updates_count': self.updates_count,
            'by_type': self._count_by_type(),
            'by_domain': self._count_by_domain()
        }
    
    def _count_by_type(self) -> Dict[str, int]:
        """Count discoveries by type"""
        counts = {}
        for disc in self._local_cache.values():
            counts[disc.discovery_type] = counts.get(disc.discovery_type, 0) + 1
        return counts
    
    def _count_by_domain(self) -> Dict[str, int]:
        """Count discoveries by domain"""
        counts = {}
        for disc in self._local_cache.values():
            for domain in disc.applicable_domains:
                counts[domain] = counts.get(domain, 0) + 1
        return counts


# =============================================================================
# SECTION 6: INTEGRATED DISCOVERY ENGINE
# =============================================================================

class Phase6DiscoveryEngine:
    """
    Complete Phase 6 Discovery Engine integrating all 5 teams.
    
    Orchestrates the flow from conjecture generation through
    formal knowledge integration.
    """
    
    def __init__(
        self,
        policy_network: PolicyNetwork = None,
        critic_network: CriticNetwork = None
    ):
        # Team 1: Conjecture Generation
        self.data_generator = SyntheticDataGenerator()
        self.pattern_recognizer = PatternRecognizer()
        self.conjecture_formalizer = ConjectureFormalizer()
        
        # Team 2: Deep Search
        self.policy = policy_network or PolicyNetwork()
        self.critic = critic_network or CriticNetwork()
        self.search_manager = SearchTreeManager(self.policy, self.critic)
        
        # Team 3: Algorithm Discovery
        self.algorithm_proposer = None  # Initialized per problem
        self.sandbox_evaluator = None
        self.heuristic_distiller = HeuristicDistiller()
        
        # Team 4: Undecidability Navigator
        self.decidability_checker = DecidabilityChecker()
        self.guidance_liaison = InteractiveGuidanceLiaison()
        
        # Team 5: Knowledge Integration
        self.formalization_pipeline = AutoFormalizationPipeline()
        self.vector_db_updater = VectorDatabaseUpdater()
        
        # Statistics
        self.conjectures_generated = 0
        self.conjectures_proven = 0
        self.algorithms_discovered = 0
        self.discoveries_integrated = 0
        
    def run_discovery_cycle(
        self, 
        num_theorems: int = 100,
        search_budget: int = 1000
    ) -> Dict[str, Any]:
        """
        Run a complete discovery cycle.
        
        1. Generate synthetic theorems
        2. Filter for interesting conjectures
        3. Assess decidability
        4. Attempt proofs
        5. Integrate discoveries
        """
        results = {
            'theorems_generated': 0,
            'conjectures_filtered': 0,
            'proofs_attempted': 0,
            'proofs_succeeded': 0,
            'discoveries_integrated': 0
        }
        
        print("=" * 60)
        print("Phase 6 Discovery Cycle")
        print("=" * 60)
        
        # Step 1: Generate synthetic theorems
        print("\n[Step 1] Generating synthetic theorems...")
        theorem_stream = self.data_generator.generate_stream(batch_size=num_theorems)
        
        # Step 2: Filter for interesting conjectures
        print("[Step 2] Filtering for interesting patterns...")
        candidate_stream = self.pattern_recognizer.filter_stream(
            theorem_stream, 
            batch_size=num_theorems // 10
        )
        
        candidates = []
        for candidate in candidate_stream:
            candidates.append(candidate)
            results['theorems_generated'] += 1
            if len(candidates) >= num_theorems // 10:
                break
        
        results['conjectures_filtered'] = len(candidates)
        print(f"   Generated {results['theorems_generated']} theorems, filtered to {len(candidates)} candidates")
        
        # Step 3: Formalize and assess decidability
        print("\n[Step 3] Formalizing and assessing decidability...")
        for candidate in candidates:
            # Formalize
            candidate = self.conjecture_formalizer.formalize(candidate)
            
            # Assess decidability
            assessment = self.decidability_checker.assess(candidate)
            
            if assessment.decidability_class == DecidabilityClass.UNDECIDABLE:
                print(f"   {candidate.conjecture_id}: UNDECIDABLE - switching to heuristic mode")
                continue
            
            # Step 4: Attempt proof
            results['proofs_attempted'] += 1
            print(f"   Attempting proof of {candidate.conjecture_id}...")
            
            # Initialize search
            self.search_manager.initialize_search(candidate)
            proof_steps = self.search_manager.search(num_simulations=search_budget)
            
            if proof_steps:
                results['proofs_succeeded'] += 1
                print(f"   ✓ Proof found: {' -> '.join(proof_steps[:3])}...")
                
                # Step 5: Integrate discovery
                discovery = self.formalization_pipeline.formalize_theorem(
                    candidate, proof_steps
                )
                self.vector_db_updater.update(discovery)
                results['discoveries_integrated'] += 1
            else:
                print(f"   ✗ Proof not found within budget")
        
        print("\n" + "=" * 60)
        print("Discovery Cycle Complete")
        print(f"  Theorems generated: {results['theorems_generated']}")
        print(f"  Candidates filtered: {results['conjectures_filtered']}")
        print(f"  Proofs attempted: {results['proofs_attempted']}")
        print(f"  Proofs succeeded: {results['proofs_succeeded']}")
        print(f"  Discoveries integrated: {results['discoveries_integrated']}")
        print("=" * 60)
        
        return results
    
    def run_algorithm_discovery(
        self,
        problem_spec: ProblemSpecification,
        generations: int = 10,
        population_size: int = 20
    ) -> Optional[Dict[str, Any]]:
        """
        Run FunSearch-style algorithm discovery.
        """
        print("\n" + "=" * 60)
        print(f"Algorithm Discovery: {problem_spec.description}")
        print("=" * 60)
        
        # Initialize components
        self.algorithm_proposer = CodeEvolutionaryProposer(problem_spec=problem_spec)
        self.sandbox_evaluator = SandboxEvaluator(problem_spec)
        
        # Initialize population
        population = self.algorithm_proposer.initialize_population(size=population_size)
        
        best_candidate = None
        best_fitness = 0.0
        
        for gen in range(generations):
            print(f"\n[Generation {gen + 1}/{generations}]")
            
            # Evaluate population
            for candidate in population:
                candidate = self.sandbox_evaluator.evaluate(candidate)
                
                if candidate.fitness_score > best_fitness:
                    best_fitness = candidate.fitness_score
                    best_candidate = candidate
            
            print(f"  Best fitness: {best_fitness:.4f}")
            
            # Early termination if perfect solution found
            if best_fitness >= 0.99:
                print("  ✓ Perfect solution found!")
                break
            
            # Evolve population
            population = self.algorithm_proposer.evolve(population)
        
        if best_candidate and best_fitness > 0.5:
            # Distill and integrate
            print("\n[Distilling heuristic...]")
            heuristic = self.heuristic_distiller.distill(best_candidate)
            
            discovery = self.formalization_pipeline.formalize_algorithm(heuristic)
            self.vector_db_updater.update(discovery)
            
            self.algorithms_discovered += 1
            
            return heuristic
        
        return None
    
    def get_system_stats(self) -> Dict[str, Any]:
        """Get comprehensive system statistics"""
        return {
            'conjectures_generated': self.data_generator.theorem_count,
            'patterns_identified': len(self.pattern_recognizer.pattern_counts),
            'search_expansions': self.search_manager.total_expansions,
            'max_search_depth': self.search_manager.max_depth_reached,
            'decidability_assessments': len(self.decidability_checker.assessment_cache),
            'pending_guidance_requests': len(self.guidance_liaison.pending_requests),
            'formalizations': self.formalization_pipeline.formalized_count,
            'vector_db_stats': self.vector_db_updater.get_stats()
        }


# =============================================================================
# DEMO
# =============================================================================

def demo_phase6():
    """Demonstrate Phase 6 Discovery Engine capabilities"""
    print("\n" + "=" * 70)
    print("PHASE 6: THE MATHEMATICAL DISCOVERY ENGINE - DEMONSTRATION")
    print("=" * 70)
    
    # Initialize engine
    engine = Phase6DiscoveryEngine()
    
    # Run discovery cycle
    print("\n[Part 1: Theorem Discovery Cycle]")
    results = engine.run_discovery_cycle(num_theorems=50, search_budget=100)
    
    # Run algorithm discovery (simplified example)
    print("\n[Part 2: Algorithm Discovery]")
    problem = ProblemSpecification(
        problem_id="subset_sum",
        description="Find if subset sums to target",
        function_signature="def solve(items, target)",
        test_cases=[
            (([1, 2, 3, 4], 6), True),
            (([1, 2, 3], 7), False),
            (([5, 10, 15], 25), True),
        ]
    )
    # Skipping actual evolution for demo
    print("  [Algorithm discovery skipped for demo brevity]")
    
    # Print final stats
    print("\n[Final System Statistics]")
    stats = engine.get_system_stats()
    for key, value in stats.items():
        print(f"  {key}: {value}")
    
    print("\n" + "=" * 70)
    print("Phase 6 Demonstration Complete")
    print("=" * 70)


if __name__ == "__main__":
    demo_phase6()
